/* =============================================================================
   conflicts.js — the discrepancy register.

   Every source in this app disagrees with some other source somewhere. Burying
   that is the single easiest way to make a research tool dishonest, because a
   clean-looking record implies a settledness the evidence does not have.

   So each known conflict is recorded here with its competing readings, who
   says what, and — where it can be said — which reading deserves more weight
   and why. Where it cannot be settled, the entry says that instead of picking.

   `status` is deliberately unflattering to this app:

     'resolved'  the app follows the best-supported reading.
     'todo'      the app still carries the weaker reading. A known defect,
                 listed here rather than quietly left in the data.
     'open'      the sources conflict and nothing available settles it.
     'flagged'   not a conflict between sources but an internal oddity in one,
                 recorded so nobody has to rediscover it.
     'withheld'  the record is not disputed, it is redacted: identified,
                 dated and acknowledged, with the content removed. Listed so
                 the timeline does not read as complete when it is not.

   Ordering within `readings` is strongest-first.
   ========================================================================== */

export const CONFLICTS = [
  {
    id: 'gofer-distance',
    subject: 'GOFER 06: distance from the Flight 93 crash site',
    tags: ['GOFER'],
    status: 'resolved',
    why: 'This is the number that decides whether the one aircraft near both crash sites was near enough to matter. It is load-bearing for the shootdown claim, so the spread matters.',
    readings: [
      { v: '"about 30 miles"', who: 'O’Brien’s own radio call to Cleveland Center at 10:06', src: 'commission', weight: 'Contemporaneous. Spoken while looking at it.' },
      { v: '~34 nautical miles', who: 'Miles Kara, radar reconstruction', src: 'press', weight: 'Instrument-derived, by the Commission’s own radar analyst.' },
      { v: '"about 20 miles off the left wing"', who: 'O’Brien, 9/11 Commission interview, 6 May 2004', src: 'commission', weight: 'Recollection, 32 months after the fact.' },
      { v: '~17 miles', who: 'Secondary retellings', src: 'press', weight: 'No stated basis. Weakest reading.' },
    ],
    reading: 'The figure got smaller with each retelling. The radio call and the radar independently agree on the larger number.',
    appSays: 'Corrected. The track now places GOFER 06 30 miles from the crash site at 10:06, matching his own radio call, with a closest approach to United 93 of 38 miles.',
    refs: ['GOFER', 'KARA_NEADS'],
  },
  {
    id: 'gofer-takeoff',
    subject: 'GOFER 06: time off the ground at Andrews',
    tags: ['GOFER'],
    status: 'resolved',
    why: 'O’Brien was held three minutes for wake turbulence behind a 747. Those three minutes are the reason he was where he was when Flight 77 came down, so the exact time is not trivia.',
    readings: [
      { v: '1333Z, 09:33 EDT', who: 'Andrews tower flight strips, cited in the Commission interview; O’Brien confirmed it', src: 'commission', weight: 'Documentary. A written record made at the time.' },
      { v: '"about 9:30"', who: 'Secondary accounts', src: 'press', weight: 'Rounded.' },
      { v: 'Scheduled for 10:00', who: 'Original flight plan', src: 'press', weight: 'Context rather than a conflict. He departed early.' },
    ],
    reading: 'The tower strip is authoritative and the pilot confirmed it, so the app uses 09:33.',
    appSays: 'Corrected. The track begins at 09:33, the 1333Z on the Andrews tower strips.',
    refs: ['GOFER'],
  },
  {
    id: 'gofer-destination',
    subject: 'GOFER 06: where it ended up',
    tags: ['GOFER'],
    status: 'resolved',
    why: 'A wrong endpoint puts a line on the map that no aircraft ever flew.',
    readings: [
      { v: 'Diverted and landed at Youngstown, Ohio', who: 'O’Brien, 9/11 Commission interview', src: 'commission', weight: 'First-hand, and he describes being debriefed there.' },
      { v: 'Continued to Minneapolis', who: 'Secondary accounts', src: 'press', weight: 'Describes the intent rather than the outcome. The crew decided to press on for Minneapolis and were then diverted.' },
    ],
    reading: 'Both are true of different moments. He intended Minneapolis and landed at Youngstown.',
    appSays: 'Corrected. The track diverts and lands at Youngstown, Ohio, instead of continuing west.',
    refs: ['GOFER'],
  },
  {
    id: 'gofer-side',
    subject: 'GOFER 06: which side the smoke was on',
    tags: ['GOFER'],
    status: 'flagged',
    why: 'A contradiction within a single source rather than between sources.',
    readings: [
      { v: '"a crew member in the tail of the plane saw some smoke off the right hand side"', who: '9/11 Commission MFR, page 4', src: 'commission', weight: 'Same document.' },
      { v: '"The sight was about 20 miles off the left wing"', who: '9/11 Commission MFR, page 4', src: 'commission', weight: 'Same document, same page.' },
      { v: '"black smoke at our nine o’clock"', who: 'Radio call at 10:06', src: 'commission', weight: 'Nine o’clock is the left side.' },
    ],
    reading: 'The MFR is a staffer’s summary rather than a transcript, and it contradicts itself within one page. The contemporaneous radio call says nine o’clock, i.e. left. Read the left-side account as correct and the other as a note-taking slip.',
    refs: ['GOFER'],
  },
  {
    id: 'gofer-tcas',
    subject: 'GOFER 06: how American 77 was spotted',
    tags: ['GOFER'],
    status: 'open',
    why: 'The mechanism of detection is cited in arguments about what the crew could have known.',
    readings: [
      { v: 'TCAS: "that is how he identified other traffic"', who: '9/11 Commission MFR', src: 'commission', weight: 'As summarised by the interviewer.' },
      { v: 'Visual: "He first sighted AAL 77 at 4,000 feet"', who: 'Same MFR, a few lines later', src: 'commission', weight: 'The rest of the account is visual throughout.' },
    ],
    reading: 'These sit awkwardly together: TCAS interrogates transponders [[transponder]], and American 77’s had been off since 08:56, so it should not have appeared. Most likely the TCAS line is a general remark about how he normally finds traffic rather than a claim about Flight 77. It is unresolved, and it is a staffer’s paraphrase rather than the pilot’s words.',
    refs: ['GOFER'],
  },
  {
    id: 'falcon-altitude',
    subject: 'The Falcon 20: how low it went over the crash site',
    tags: ['UA93'],
    status: 'open',
    why: 'The Falcon is the "mystery white jet" of Flight 93 folklore. How low it flew is what people argue about.',
    readings: [
      { v: 'Circled at 6,000–6,500 ft, 10:11–10:15', who: 'Miles Kara, radar reconstruction', src: 'press', weight: 'Instrument-derived, with times.' },
      { v: 'Descended to within ~1,500 ft of the ground', who: 'Co-pilot Yates Gladwell, via Popular Mechanics', src: 'press', weight: 'First-hand, but recollection.' },
    ],
    reading: 'Radar and memory disagree by several thousand feet. Neither is obviously wrong, since a crew can descend between sweeps, but the radar timing is firm and is the better number to quote. Under either reading the Falcon arrived 8–12 minutes after impact and saw only the aftermath.',
    refs: ['KARA_NEADS'],
  },
  {
    id: 'ua93-impact-time',
    subject: 'United 93: time of impact',
    tags: ['UA93'],
    status: 'resolved',
    why: 'A later impact time would open a window for an intercept, so this is the single most contested timestamp of the morning.',
    readings: [
      { v: '10:03:11', who: 'NTSB, from the recovered flight data recorder', src: 'ntsb', weight: 'Physical recorder aboard the aircraft. Decisive.' },
      { v: '10:06', who: 'Extrapolation from a seismic study (Kim and Baum)', src: 'claim', weight: 'The lead author later agreed the data were inconclusive for United 93.' },
    ],
    reading: 'A flight data recorder [[fdr]] beats a seismic inference, and the lead author conceded the point, so the app uses 10:03:11.',
    appSays: 'The app uses 10:03:11 throughout.',
    refs: ['UA93', 'DEBRIS'],
  },
  {
    id: 'ua93-altitude',
    subject: 'United 93: altitude profile',
    tags: ['UA93'],
    status: 'resolved',
    why: 'This app renders altitude on a vertical axis, so getting the profile wrong misrepresents the thing it exists to show.',
    readings: [
      { v: 'Climbs to 41,000 ft at 09:39; down to 5,000 ft by 09:59; back to ~10,000 before impact', who: 'NTSB Flight Path Study, Figure 2 (FDR)', src: 'ntsb', weight: 'Flight data recorder.' },
      { v: 'Level near 35,000 ft until a late descent', who: 'This app, until corrected', src: 'derived', weight: 'Guessed from narrative. Wrong.' },
    ],
    reading: 'The FDR profile is now plotted. The earlier version missed the climb to 41,000 entirely and flew the aircraft at cruise altitude through a descent that reached 5,000 ft.',
    appSays: 'Corrected. UA93 altitudes are now tagged NTSB / FDR.',
    refs: ['UA93'],
  },
  {
    id: 'gofer-callsign',
    subject: 'GOFER 06: callsign rendering',
    tags: ['GOFER'],
    status: 'open',
    why: 'Minor, but callsigns are how you find an aircraft in a transcript.',
    readings: [
      { v: 'GOFER 06', who: 'Commission MFR, ATC transcripts, the pilot’s own account', src: 'commission', weight: 'Overwhelming majority.' },
      { v: 'Gofer 86', who: 'At least one otherwise careful callsign roster', src: 'press', weight: 'Isolated.' },
    ],
    reading: 'GOFER 06 is almost certainly right; the variant is recorded so a reader who meets it elsewhere knows it is the same aircraft.',
    refs: ['GOFER', 'AVIATIONIST'],
  },
  {
    id: 'andrews-callsign',
    subject: 'Andrews DC ANG: flight callsigns',
    tags: ['BULLY'],
    status: 'open',
    why: 'The app draws a track labelled BULLY and should not pretend that label is settled.',
    readings: [
      { v: 'BULLY / WILD / CAPS', who: 'Callsign roster of the day’s air defence response', src: 'press', weight: 'Specific to 9/11.' },
      { v: 'BULLDOG', who: 'The 121st Fighter Squadron’s historical squadron callsign', src: 'press', weight: 'Correct for the unit generally; may not be what was used that morning.' },
    ],
    reading: 'Unsettled. The app uses BULLY and says so in the callsign reference.',
    refs: ['BULLY', 'AVIATIONIST'],
  },
  {
    id: 'gibney-rank',
    subject: 'Rick Gibney: rank',
    tags: ['CLAIM'],
    status: 'resolved',
    why: 'It is the only checkable detail the claimant offers about the man he names.',
    readings: [
      { v: 'Lieutenant Colonel', who: 'North Dakota Air National Guard', src: 'press', weight: 'His own service.' },
      { v: '"Major"', who: 'Donn de Grand-Pre, 2004', src: 'claim', weight: 'Wrong.' },
    ],
    reading: 'He was a lieutenant colonel, not a major.',
    appSays: 'Noted in the claim tab.',
    refs: ['CLAIMANT', 'GIBNEY'],
  },
  {
    id: 'claim-time',
    subject: 'The alleged shootdown: what time is being claimed',
    tags: ['CLAIM'],
    status: 'resolved',
    why: 'The claim has drifted since it was made, and the drift is toward making it fit.',
    readings: [
      { v: '"that was hit at 10:00 hours"', who: 'Donn de Grand-Pre, as spoken, February 2004', src: 'claim', weight: 'The original wording.' },
      { v: '09:58', who: 'Later retellings', src: 'claim', weight: 'Hardened after the fact.' },
      { v: '10:03:11', who: 'What actually happened, per the FDR', src: 'ntsb', weight: 'Neither claimed time matches it.' },
    ],
    reading: 'The claimed moment moved. Neither version lines up with the recorder, which puts impact at 10:03:11, so the allegation does not match the event it describes.',
    appSays: 'The app tests 09:58, the more favourable of the two for the claim.',
    refs: ['CLAIMANT', 'UA93'],
  },
  {
    id: 'rades-outage',
    subject: '84th RADES: a claimed gap in radar coverage',
    tags: ['DATA'],
    status: 'open',
    why: 'If true it would matter for every radar-based argument about the day, including the ones this app relies on second-hand.',
    readings: [
      { v: 'RADES coverage dropped out for a period on 9/11', who: 'Attributed to Charlie Kallas via Miles Kara', src: 'claim', weight: 'Second-hand attribution. Not independently confirmed here.' },
      { v: 'No such gap asserted', who: 'The NTSB and Commission studies built on RADES data', src: 'commission', weight: 'Silence, not denial.' },
    ],
    reading: 'Unverified either way. Recorded because it circulates and because this app cites RADES-derived analysis without having seen the files.',
    refs: ['KARA_NEADS'],
  },
  {
    id: 'track-provenance',
    subject: 'This app’s flight tracks are not radar data',
    tags: ['DATA'],
    status: 'open',
    why: 'A smooth line on a 3D map reads as measurement. Two of these four are not.',
    readings: [
      { v: '~4.8-second sweeps, several hundred points per flight', who: 'What real 84th RADES data looks like', src: 'press', weight: 'The standard this app does not meet.' },
      { v: '9–12 hand-placed waypoints, one per ~6 minutes', who: 'AA11 and UA175 in this app', src: 'derived', weight: 'Interpolated with great circles between anchors. Neither recorder was ever recovered, so nothing better exists to use.' },
      { v: 'FDR altitudes and timings throughout; the UA93 ground track now a 320-point supplied polyline, AA77 still traced by eye', who: 'UA93 and AA77 in this app', src: 'ntsb', weight: 'Vertically sound for both. Laterally, UA93 is now dense and checks out against all nine lettered anchors in the study; AA77 remains approximate.' },
    ],
    reading: 'No RADES file is plotted anywhere in this app, and none will be until someone reads the files. What has changed is the split: AA77 was rebuilt from its own NTSB Flight Path Study, so the two flights whose recorders survived now carry recorder altitudes: the 25,000 ft level-off, the three-minute autopilot disconnect that sags to 22,000, and the final 330-degree turn. AA11 and UA175 remain what they always were, and are badged accordingly. This entry stays open permanently as a standing caveat about the medium.',
    appSays: 'AA11 and UA175 are badged RECONSTRUCTED. Altitudes and timings for UA93 and AA77 are badged NTSB / FDR. The UA93 ground track is badged GEO: a 320-point polyline supplied to the project, validated against the nine lettered anchors in the study but not itself an NTSB product. The AA77 ground track is still traced by eye and stays approximate.',
    refs: ['UA93', 'AA77'],
  },
];

CONFLICTS.push(
  {
    id: 'backchannel-tasking',
    subject: 'Could a channel outside NORAD have tasked a fighter at United 93?',
    tags: ['AWARENESS', 'STEELMAN'],
    status: 'resolved',
    why: 'This app argued that nobody could have guided the fighter, and rested it on the air defence sector not hearing the words United 93 until 10:07. A reader pointed out that the argument never addressed the channel that demonstrably did task fighters that morning without NORAD, and they were right that its absence weakened the case.',
    readings: [
      { v: 'The backchannel is real and it worked', who: '9/11 Commission, ch. 1', src: 'commission',
        weight: 'The Secret Service reached the DC Air National Guard directly. Fighters launched from Andrews on authority relayed from the White House rather than through NORAD. Whatever else is true, a parallel channel existed and produced aircraft.' },
      { v: 'And it was slower than the chain it bypassed', who: 'The same source', src: 'commission',
        weight: 'Its first fighter left Andrews at 10:38 and its second at 10:42, thirty-five and thirty-nine minutes after United 93 was already in the ground. Neither of the first two carried live ammunition.' },
      { v: 'What the Secret Service reported was a projection, and no fighter was cleared to fire', who: '9/11 Commission Report, ch. 1', src: 'commission',
        weight: 'At 10:02 the Secret Service began reporting an inbound aircraft, United 93, from FAA information, "relying on projections". The Langley pilots "never received any type of engagement order", and shortly after 10:10 they were told "negative clearance to shoot".' },
      { v: 'Its first contact with the Langley fighters came at 10:28', who: 'Miles Kara, "9-11: The Andrews Fighters; A Complex Story, itself chaotic" (audio clip 102838), and his audio clips page', src: 'press',
        weight: '"At that time, 1028, the Secret Service first made sure they were in contact with Quit 25, the Langley lead pilot, via National TRACON on the DCA approach frequency. Quit 25 changed frequency to allow that." That is twenty-five minutes after United 93 was down. Kara places the Secret Service request for fighter cover at 09:48 to 09:50, after the Pentagon was struck, passed through FAA headquarters to Andrews tower, for fighter support over the White House for the return of Air Force One. The Langley fighters were on combat air patrol over the capital from 10:00.' },
      { v: 'The track it was working from was not the aircraft', who: 'Miles Kara, the same post', src: 'press',
        weight: 'The Secret Service was acting on a notional United 93 track on an FAA traffic situation display, which "faded at 1028 when the notional United 93 \'landed\' at Reagan National". The false report that United 93 had crashed at Camp David also came from the Secret Service.' },
      { v: 'The lead pilot says a radio call alone would not have been acted on', who: 'Dean Eckmann, Langley lead pilot, InForum, 25 August 2011', src: 'press',
        weight: '"If someone just says on the radio, \'Go shoot that airplane down,\' we\'re not going to do it. We have a process."' },
      { v: 'It reached North Dakota Guard pilots at Langley, not Gibney at Fargo', who: 'Computed here, corrected', src: 'derived',
        weight: 'This reading was first headed It also does not reach North Dakota, and that was wrong. Quit 25 was a North Dakota Air National Guard F-16 on the Langley alert detachment, and the Secret Service was in contact with it from 10:28. The narrower point still holds: the arrangement ran between the executive and units guarding the capital, about an aircraft believed to be inbound to the capital, and nothing resembling it connects the Secret Service to a transport tasking at Fargo.' },
      { v: 'And no civil or executive body can vector an intercept', who: 'Computed here', src: 'derived',
        weight: 'Knowing where an aircraft is and being able to steer a fighter onto it are different capabilities. The second needs a weapons controller holding a track, which is precisely what nobody had before 10:07.' },
    ],
    reading: 'The objection survives the form the app first gave it and fails on the clock. The channel existed, it bypassed NORAD, and it worked - and it delivered unarmed fighters more than half an hour after the aircraft was down. But it does not end there, because the CRITIC is itself a backchannel, and the fastest one the system has. A CRITIC exists to put something in front of the President inside ten minutes, going around normal reporting entirely. So the executive channel this objection depends on was demonstrably carrying flash traffic at 09:49, forty-nine minutes before the same channel produced an aircraft at Andrews, and its first two aircraft were unarmed. That is the honest shape of it: the executive channel was awake early and slow to deliver. And the CRITIC is where this objection is strongest rather than weakest, because unlike the Andrews launch its content is withheld. Nobody can say what the 09:49 message contained. What can be said is that a CRITIC goes to intelligence watch floors, not to fighter units. Contact between the executive chain and the fighters that morning is now documented, and it supports the same conclusion, that the channel could not task an intercept. The Secret Service asked for fighter cover over the White House at 09:48 to 09:50, for the return of Air Force One, and its first aircraft left Andrews at 10:38. It first made sure of contact with Quit 25, the Langley lead, at 10:28, twenty-five minutes after United 93 was down. And it was following a projected United 93 track that ended in a notional landing at Reagan National, not the aircraft.',
    appSays: 'Problem 2 now answers the backchannel directly rather than answering only the FAA. The timing, the geography and the capability gap are all stated, and the concession that the channel was real comes first. The app also says plainly where this leaves the claim: of every channel examined, the CRITIC is the only one whose content is withheld and whose timing sits inside the window. That is why this project is named after it, and it is the reason the four messages are the single most valuable thing anyone could still ask for. This register had also said the channel did not reach North Dakota at all. That was wrong and the reading is corrected: the Secret Service was in contact with Quit 25, a North Dakota Guard pilot at Langley, from 10:28. Problem 2 says only that nothing like the channel connects to a transport tasking in North Dakota, and that stands.',
    refs: ['COMMISSION', 'KARA_ANDREWS', 'INFORUM_2011'],
  },
  {
    id: 'fdr-parameter-audit',
    subject: 'Which recorder channels is this app entitled to cite?',
    tags: ['DATA', 'FDR'],
    status: 'resolved',
    why: 'The app had been treating a parameter appearing in the published tabulation as proof the parameter was good. It is not. The tabulation carries channels the NTSB marked as not working, so every citation needed checking against the attachment that says which is which.',
    readings: [
      { v: 'Confirmed on the validated list, by direct reading', who: 'NTSB DCA01MA065, Attachments I-2 to I-6', src: 'ntsb',
        weight: 'ROLL ANGLE CAPT and ROLL DISAGREE CAPT, at the tail of I-5 between REVERSER STATUS and RUDDER. PITCH ANGLE CAPT and PASS OXY ON, also I-5, alongside lateral and longitudinal acceleration. ENG EPR-ACTUAL L and R, ENG FUEL FLOW L and R, ENG FUEL CUTOFF L and R, at the tail of I-2. ENGINE FIRE and ENGINE OVHT L and R, and ENG VIBRATION R, on I-3. HYD PRES and HYD SYS LO PRESS, all three systems, on I-4. RUDDER POSITION and RUDDER PEDAL POSN on I-6. CABIN ALT above 10kft, CONTROL COLUMN and CONTROL WHEEL POSN-CAPT and COMPUTED AIRSPEED on I-2.' },
      { v: 'Once resting on absence rather than sight, now read directly', who: 'NTSB DCA01MA065, Attachments I-1, I-3 and I-7', src: 'ntsb',
        weight: 'An earlier pass left ENG N1-ACTUAL, ENG N2-ACTUAL, VERTICAL ACCELERATION and ALTITUDE resting on absence: none appears on the not-working list, and their alphabetical neighbours on it run contiguously past where each would fall. All four have since been seen on the validated list. ENG N1-ACTUAL and ENG N2-ACTUAL, left and right, are on I-3. VERTICAL ACCELERATION, all eight channels, is on I-7, which covers the channel the 4.148 g figure rests on. ALTITUDE (1013.25mB), coarse and fine, is on I-1.' },
      { v: 'Validation is per channel, not per parameter', who: 'The same attachments', src: 'ntsb',
        weight: 'ENG EPR COMMAND - L is on the validated list at I-2. ENG EPR COMMAND - R is on the not-working list at I-8. Same parameter, two channels, opposite status. No parameter can be cleared in the plural.' },
      { v: 'Not working or unconfirmed, and withdrawn', who: 'The same report, Attachments I-8 to I-10', src: 'ntsb',
        weight: 'Hydraulic reservoir quantity, all three systems. Engine vibration identifiers. Engine EGT left and right, EPR command right, fuel pressure left and right, bleed off. Yaw damper engage left and right. Total fuel quantity, static air temp, rudder PCU, true heading, altitude reporting and altitude select. The app had cited the first of these and no longer does.' },
      { v: 'And one loose end closes itself', who: 'Computed here from the two lists', src: 'derived',
        weight: 'An earlier pass found that the recorded rudder moved through more than two degrees while the rudder pedal barely shifted, correlating at minus 0.055, and flagged it as unexplained. Rudder position and rudder pedal position are both on the validated list, so the measurements are sound and the discrepancy between them is real. What explains it is the yaw damper, which moves the rudder independently of the pedals as a matter of design; only its engage channels, L and R, are on the not-working list, while YAW DAMPER - L, YAW DAMPER - R and YAW DAMPER MODULE are validated at I-7 and read OK throughout, which supports that explanation. The yaw axis was never evidence of anything and is excluded.' },
    ],
    reading: 'The audit comes out clean for everything the argument needs. It had to be done twice to get there: the first pass was reported as complete while roll angle rested on a subagent report of a page nobody here had opened and the engine channels rested on absence from a list read in fragments. Both now hold on direct reading. The four channels it then left resting on absence rather than sight have since been read directly as well. What it did produce is the rule: presence in the tabulation is not a validation certificate, and the attachment that decides it is a separate document from the one carrying the numbers.',
    appSays: 'Every recorder figure in this app is now traceable to the validated list. Where a channel is unvalidated the app says so and does not use it, including the reservoir quantity readings it briefly cited and the yaw axis it briefly puzzled over.',
  },
  {
    id: 'hydraulic-channel-blind-spots',
    subject: 'How much can the hydraulic channels actually see?',
    tags: ['DATA', 'FDR'],
    status: 'flagged',
    why: 'The app leans on the hydraulic channels to argue that no cascade of system failures occurred. A reader asked whether those channels have blind spots of the same kind as the cabin altitude discrete. They have three, and nobody here had looked.',
    readings: [
      { v: 'The discrete is threshold-limited and cannot see partial loss', who: 'NTSB DCA01MA065 parameter set', src: 'ntsb',
        weight: 'HYD SYS LO PRESS is a two-state discrete. It reports whether pressure has fallen past a trip point, and nothing else. A system bleeding down while staying above that point reads NORMAL the whole way.' },
      { v: 'The analogue pressure channel stops before the dive does', who: 'Read directly from the tabulation', src: 'ntsb',
        weight: 'HYD PRES appears once every 64 seconds in the NTSB published tabulation, 79 samples across the flight. But that is the publication, not the recorder: the parameter database defines it at 0.5 Hz, in subframes 1 and 3 of every frame, which is one sample every two seconds. The tabulation is decimated by a factor of thirty-two. The last sample on the left system is 10:02:18, on the centre 10:02:26 and on the right 10:02:34, which is 53, 45 and 37 seconds before impact. Exactly one sample each falls after 10:02:00. Reservoir pressure ends at 10:02:55 and reservoir quantity at 10:03:03.' },
      { v: 'So the final forty seconds carry only the discrete', who: 'Computed here', src: 'derived',
        weight: 'The roll past ninety degrees at 10:03:03 and the whole of the steep dive sit inside a window with no analogue hydraulic data of any kind. The only hydraulic channel running at a useful rate to the end is the one with the threshold problem, at 2,525 samples to 10:03:08.' },
      { v: 'And the quantity discrete is not all-normal', who: 'The same tabulation', src: 'ntsb',
        weight: 'HYD SYS LO QTY reads LO QTY on 45 of 79 samples on the left system, 32 of 79 on the right, and 2 on the centre. The last right-system sample, at 10:03:03, reads LO QTY.' },
      { v: 'But the NTSB had already disqualified those channels, and this app cited them without checking. HYD SYS LO QTY - C, - L and - R all appear on Attachment I-9, Parameters Not Working or Unconfirmed. The toggling is therefore exactly what it looks like', who: 'Computed here', src: 'derived',
        weight: 'The indication begins at 08:39:51, before the aircraft went anywhere, and toggles both directions throughout: low, normal, low, normal. Real fluid loss is monotonic. This is a reservoir sensor sitting near its threshold while fluid moves and actuators cycle, and it is noise.' },
      { v: 'An unexplained figure sits alongside it', who: 'The same tabulation', src: 'ntsb',
        weight: 'The analogue channels read 1,488 to 1,860 psi against a 3,000 psi nominal 757 system, roughly 55 to 62 per cent, steady from 08:39 onward. The decode is not the explanation: the United parameter database for this airframe defines HYD PRES as ten bits, y = 4x + 0, range 0 to 4,092 psi, and all 237 published values are exact multiples of 4, sitting between counts 372 and 465 of 1,023. The scaling is right and the numbers are on its lattice. Nor is validation the explanation. Attachment I-4 of the factual report, the list of parameters the NTSB validated, contains HYD PRES - C, - L and - R by name, sourced from port EICAS L/R-A-1. The Board read these values out and accepted them. So the figure is correctly decoded and formally validated, and it is still about 57 per cent of what a 757 supply system is usually quoted at. The weakest link in calling it anomalous is the comparison itself: the 3,000 psi nominal is an assumption brought to the data rather than a figure taken from a document for this airframe, and the parameter is sourced from the crew display bus rather than from a supply transducer. The anomaly may be in the baseline.' },
    ],
    reading: 'The blind window is withheld, not absent, and that is the distinction this app says matters most. The recorder was sampling hydraulic pressure every two seconds and the published attachment shows it every sixty-four. So the final forty seconds are missing from the tabulation, not from the recording, and the raw file would carry roughly twenty more samples per system across exactly the interval in question. That is filable. As published, the cascade argument survives for any engagement before about 10:02:18 and goes blind after it. That distinction matters and the app had not been drawing it. Every documented cascade in the comparison set is fast - hydraulic system 3 to zero within three seconds at Aktau, two systems lost immediately at Baghdad - so a warhead functioning at any point in the long window before 10:02:18 would have been caught by the analogue channels, which sampled right through it. A warhead functioning inside the final forty seconds would not.',
    appSays: 'A general lesson came out of this that applies beyond hydraulics. HYD SYS LO QTY appears in the published tabulation AND on the not-working list, so presence in Attachment III is not a validation certificate. Every parameter this app cites has to be checked against Attachment I. That audit has now been done and is recorded at fdr-parameter-audit. The app no longer says the hydraulic systems read normal to impact. It says the low-pressure discrete reads normal on all 2,525 samples to 10:03:08, names the threshold limit, names the 64-second sampling, and states the size of the blind window. The quantity chatter is reported rather than omitted, with the reason it is not a failure signature.',
  },
  {
    id: 'ua93-pdb-prior-reporting',
    subject: 'What does the second sentence of the al-Ghamdi paragraph refer to, and when?',
    tags: ['CRITIC', 'AWARENESS', 'FOIA'],
    status: 'open',
    why: 'The app quoted the first sentence of a two-sentence paragraph and left out the second, which is the half that cuts against the use the app was making of the document. Quoting the convenient half of a source is the exact failure this project exists to avoid, so the whole paragraph is here.',
    readings: [
      { v: 'The paragraph in full, redactions marked', who: 'CIA, Situation Report: Bin Ladin Tracks, 12 September 2001, 0400 EDT, page 1', src: 'foia',
        weight: 'REDACTED indicates a possible terrorist operative, named al-Ghamdi, may have boarded United Airlines flight 175, one of the aircraft that struck the World Trade Center. REDACTED an individual with a similar name would enter the US via Canada to carry out a terrorist attack in New York.' },
      { v: 'The second sentence probably refers to reporting held before the attacks', who: 'Read from the page, not from the grammar', src: 'derived',
        weight: 'Every fresh item on page 1 is dated in the clear: on Sunday, yesterday, late last month, in mid-June. On the two occasions where a blacked-out source is followed by a date, the date falls outside the bar, so this document redacts who reported rather than when. The al-Ghamdi paragraph carries no date at all. That absence is the argument. The tense is not: would enter is future-in-the-past and fixes the report as earlier than the planned entry, not earlier than 11 September.' },
      { v: 'But the CIA declined to identify the two people as the same man', who: 'The same paragraph', src: 'foia',
        weight: 'A SIMILAR name, written one sentence after named al-Ghamdi, with the exact string available and not used. And MAY HAVE boarded. Both hedges are the CIA own words. They are what an agency writes when it runs a name against a manifest and the run comes back inconclusive.' },
      { v: 'The Canada detail fails as corroboration', who: '9/11 Commission staff report on terrorist travel', src: 'commission',
        weight: 'Ahmed al Ghamdi arrived at Dulles on 2 May 2001, Hamza al Ghamdi at Miami on 28 May, Saeed al Ghamdi at Orlando on 27 June after a secondary inspection. The staff counted 34 entry attempts through nine airports across 21 months. No conspirator entered overland from Canada.' },
      { v: 'Real pre-attack Canada reporting did exist, and it named nobody', who: 'Joint Inquiry report, printed page 204', src: 'commission',
        weight: 'In May, the Intelligence Community obtained a report that Bin Ladin supporters were planning to infiltrate the United States by way of Canada to carry out a terrorist operation using high explosives. Shared in July with FBI, INS, Customs and State, and carried into an August product for senior officials, which is the 6 August brief, with the Canada element removed. The Commission traces the stream to an anonymous call to a US embassy that could not be corroborated. High explosives, not hijacking. No name, no city.' },
      { v: 'No al-Ghamdi appears in the body of the report that exists to catalogue what was known', who: 'Full-text search of the 838-page declassified Joint Inquiry', src: 'derived',
        weight: 'Three hits for every spelling variant, all three in a pronunciation guide inside an appendix listing the hijackers. Not one in the body.' },
    ],
    reading: 'Open on the date, closed on the identification. The look-back reading is the better one and is badged derived rather than stated as fact, because a liaison report received on the evening of the eleventh produces the same sentence. The identification is settled the other way by the document itself, twice, in the CIA own hedges. What survives is narrower than it first looks and worth keeping: the United States held pre-attack reporting about entering via Canada to attack inside the country, it reached the President on 6 August with the Canada element stripped out, and whether any of it carried a name resembling a hijacker is exactly what the second redaction hides.',
    appSays: 'The app states the paragraph in full, treats the prior-reporting reading as probable rather than established, and says plainly that none of it bears on Flight 93: the passage names flight 175, Saeed al-Ghamdi was aboard 93 and is not its subject, and the only link is a tribal surname the document itself flags as merely similar. It is filed under awareness and walled off from the shootdown case.',
  },
  {
    id: 'warhead-signature-cascade',
    subject: 'What a missile actually leaves on a flight recorder',
    tags: ['DATA', 'FDR', 'STEELMAN'],
    status: 'resolved',
    why: 'This app argued for a while that a recorder running to impact told against a warhead. A reader pointed out that a Sidewinder functions on a proximity fuze rather than by striking the aircraft, so it need not touch the recorder or its power at all. That is correct, and checking it against the comparison set showed the original argument was simply wrong.',
    readings: [
      { v: 'Most recorders in real missile cases keep running', who: 'Accident reports for the recovered cases', src: 'ntsb',
        weight: 'A DHL A300 hit in the left wing by a MANPADS over Baghdad recorded for twenty-five more minutes and landed. An Embraer 190 near Aktau recorded for about seventy-five minutes to ground impact after two detonations near the tail. KAL 007 recorded for a hundred and four seconds after an R-98 functioned roughly fifty metres behind it. PS752 recorded through the detonation itself. Only the bomb cases, where the explosion sat near the recorder power path, stopped abruptly.' },
      { v: 'The acceleration channels cannot see a warhead either', who: 'Dutch Safety Board, MH17 final report, section 3.4.1', src: 'ntsb',
        weight: 'A 70 kg warhead functioned two to four metres from the nose. The board states that all three acceleration axes showed stable data to the end of the recording, and separately that the blast wave audible in the last twenty milliseconds of the voice recorder could not be observed in the acceleration data at all. They looked for it and reported that it was not there.' },
      { v: 'What every case does show is a systems cascade', who: 'The same reports', src: 'ntsb',
        weight: 'Aktau, timed off its own recorder: hydraulic system 3 to zero at plus three seconds, pitch trim failure at plus five, depressurisation beginning at plus eight, hydraulic system 1 to zero at plus sixteen. Baghdad: two hydraulic systems lost immediately and the third about twenty seconds later. KAL 007: hydraulic systems 1, 2 and 3 lost, with damaged elevator cabling driving a 113-second uncommanded pitch-up.' },
      { v: 'United 93 has no cascade', who: 'NTSB DCA01MA065 tabulation, read directly', src: 'ntsb',
        weight: 'HYD SYS LO PRESS C, L and R read NORMAL on all 2,525 samples, the last at 10:03:08. That is a threshold discrete, not a pressure measurement, and the analogue pressure channels stop between 37 and 53 seconds before impact. Both engines run to 10:03:06 with EPR tracking left to right at a mean difference of 0.007. Engine fire and overheat read NORMAL throughout. Control wheel to aileron correlates at minus 0.985 and control column to elevator at plus 0.944, with the surfaces still answering two seconds before impact.' },
    ],
    reading: 'The original argument is withdrawn. A proximity-fuzed weapon can leave a recorder running, and the acceleration channels are the wrong place to look in any case. The argument that replaces it is stronger and rests on the same comparison set: in every recovered missile case the recorder documents a cascade of system failures within seconds, and United 93 documents none. The distinction that matters is not whether the recording stopped but whether the aircraft systems started dying, and on the flight data they did not.',
    appSays: 'The walkthrough no longer claims that a warhead normally stops a recorder. It states the cascade test instead, and names the two cases where recorders ran for twenty-five and seventy-five minutes after a hit. One concession stands: KAL 007 stopped after 104 seconds and the aircraft then flew roughly ten more minutes unrecorded, so a recorder can stop late as well as early.',
  },
  {
    id: 'pdb-12sep-silent-on-93',
    subject: 'What the CIA told the President the morning after',
    tags: ['CRITIC', 'AWARENESS'],
    status: 'resolved',
    why: 'If anyone had precise early knowledge of what happened over Pennsylvania, the daily briefing written for the President seventeen hours later is a reasonable place to look for a trace of it.',
    readings: [
      { v: 'One flight is named in the whole document, and it is not United 93', who: 'CIA, Situation Report: Bin Ladin Tracks, 12 September 2001, 0400 EDT, declassified 11 September 2026', src: 'foia',
        weight: 'The report says a possible operative named al-Ghamdi may have boarded United Airlines flight 175. Both verbs are hedged. Three men named al-Ghamdi flew that morning: two on 175 and Saeed al-Ghamdi on 93, the man Jarrah calls by name on the cockpit tape at 10:00:37.' },
      { v: 'Flight 93 does not appear at all', who: 'The same document, all four pages', src: 'foia',
        weight: 'No mention of the flight, of Shanksville, of Pennsylvania, of a fourth aircraft, of NORAD, of a shootdown, or of a CRITIC.' },
      { v: 'NSA was in the same position a day later', who: 'NSA CRITIC summary 131303Z SEP 01', src: 'foia',
        weight: 'Its released comment paragraph sources the crash to press reporting, puts the origin of United 93 at JFK rather than Newark, and brackets the impact time to within an hour.' },
    ],
    reading: 'Two agencies, two independent document streams, neither showing precise knowledge of the Shanksville crash the following morning. One thing this entry got wrong at first and a reader caught: the paragraph is two sentences doing two different jobs, and the app quoted only the first. The second reaches back into reporting the community appears to have held already. See ua93-pdb-prior-reporting. That is the second corroboration of a finding the app already held, and it arrived from a direction nobody was watching. The honest limit is that a daily brief is a summary written for one reader, not an inventory of what an agency holds, and this one is heavily redacted, including the passage immediately before the sentence naming flight 175.',
    appSays: 'The app treats the CIA product as corroboration rather than proof, and notes that the release stops on 28 August 2001 and resumes on 12 September. Whether daily briefs for 10 and 11 September exist and were withheld, or were simply not selected, is not stated anywhere in the release.',
  },
  {
    id: 'ua93-target-capitol',
    subject: 'Where was United 93 going?',
    tags: ['DATA', 'AWARENESS'],
    status: 'resolved',
    why: 'The app has argued from geometry that the target was Washington. Geometry alone is a thin basis for a claim about intent, and until now there was nothing else.',
    readings: [
      { v: 'The heading flown matches the Capitol to within one degree', who: 'Computed here from the radar ground track', src: 'derived',
        weight: 'From the turnaround west of Cleveland the Capitol bears 118.4 degrees and Newark bears 91.9. The track settles on 117.5. The NTSB records that the turn was flown with the autopilot in heading select mode.' },
      { v: 'Intelligence reporting named the same target, from a different source stream', who: 'CIA, Situation Report, 12 September 2001', src: 'foia',
        weight: 'The report says reporting suggests the Capitol and the White House also may have been targets, and cites an intercept in which someone gave thanks for the explosion in the Congress building. It makes no reference to any flight path.' },
      { v: 'People inside the network believed a Washington target had been hit', who: 'The same document', src: 'foia',
        weight: 'A member of an organisation sympathetic to Bin Ladin initially claimed the White House had been destroyed before correcting himself. Nobody in that traffic knew the fourth aircraft had failed.' },
    ],
    reading: 'Two independent lines now point at the Capitol: a radar track and a signals intercept, neither derived from the other. The announcement to the cabin at 09:39, that they were going back to the airport, was a pacifier and never named an airport.',
    appSays: 'The app states the Capitol as the probable target and shows both lines of support, with the geometry badged derived and the intercept badged as a declassified CIA product.',
  },
  {
    id: 'ua93-cabin-pressure-blind',
    subject: 'The one thing the flight data recorder could not have seen',
    tags: ['DATA', 'FDR'],
    status: 'flagged',
    why: 'Almost every channel an external event would disturb was recorded and is undisturbed. This is the exception, and it is set down deliberately rather than left out, because an argument that only lists what it wins is not worth reading.',
    readings: [
      { v: 'No cabin altitude or differential pressure channel exists in the data frame', who: 'NTSB DCA01MA065 parameter list, read directly', src: 'ntsb',
        weight: 'The entire 937-row frame contains one pressurisation parameter: the discrete CABIN ALT > 10kft. There is no analogue cabin altitude and no cabin differential pressure anywhere.' },
      { v: 'That discrete reads NORMAL on all 5,050 samples', who: 'The same tabulation', src: 'ntsb',
        weight: 'Last sample 10:03:09. It is a genuine reading, and it does establish that cabin altitude never exceeded 10,000 ft.' },
      { v: 'But it is blind in exactly the window that matters', who: 'Computed here', src: 'derived',
        weight: 'The discrete trips on CABIN altitude above 10,000 ft, and cabin altitude can never exceed aircraft altitude, because a breach equalises the cabin to outside pressure rather than taking it higher. United 93 crossed below 10,000 ft at 09:54:51 and never regained it: the maximum afterwards is 9,981 ft, and the later climb tops out at 9,902 ft at 10:02:15. So from 09:54:50 to the last sample at 10:03:09, eight minutes and nineteen seconds, a total hull breach would have left this channel reading NORMAL. The revolt begins 130 seconds inside that window. The same limit applies to PASS OXY ON, since masks deploy on a cabin altitude of about 14,000 ft, so that parameter is blind in the same window and is not evidence against a breach in it.' },
    ],
    reading: 'Open, and it cannot be closed from the recorder. Every other channel that an external event would mark is recorded and clean: three hydraulic systems normal to 10:03:08, both engines running to 10:03:06 and symmetric throughout, engine fire and overheat normal, the recorder itself writing without a gap to the last second. Cabin pressure is the single gap in that audit, and the aircraft spent the whole of the critical period inside the gap. This does not support a breach. It means the recorder cannot rule one out.',
    appSays: 'The app treats the absence of cabin pressure data below 10,000 ft as a known limit on its own argument, not as a point in its favour. The passenger oxygen system is a separate matter and is answered: PASS OXY ON reads OFF on all 79 samples with no transition, so the masks never deployed.',
  },
  {
    id: 'ua93-engines-commanded',
    subject: 'Did the hijackers shut the engines down?',
    tags: ['DATA', 'CRASH', 'CVR'],
    status: 'resolved',
    why: 'Two English words sit inside otherwise Arabic lines on the voice recorder: engine at 10:01:11, and Shut them off at 10:02:03. If an engine had been shut down deliberately, the engine parameters would show a loss that was commanded rather than inflicted, and that is the difference between a crew acting and a weapon acting. The question had not been asked, and the flight data recorder answers it outright.',
    readings: [
      { v: 'No engine was shut down', who: 'NTSB DCA01MA065, Digital Flight Data Recorder Specialist factual report, 15 Feb 2002, tabulated parameters', src: 'ntsb',
        weight: 'ENG FUEL CUTOFF - L and - R read RICH/RUN on all 79 recorded samples. ENG FUEL VALVE - L and - R read NORMAL on all 79. ENG OUT RLY - L and - R read ENG RUN on 1,262 and 1,263 samples, the last at 10:03:06 and 10:03:08. Both engines were running to within five seconds of impact.' },
      { v: 'But both thrust levers were pulled to idle, and the command is on the tape first', who: 'The same tabulation, read against the FBI transcript', src: 'ntsb',
        weight: 'Thrust peaks at 10:02:09 to 10:02:14 (EPR 1.197, N1 84). Retardation begins at 10:02:17 and both engines are at idle by 10:02:45 (N1 34, fuel flow 768 to 1,024 lb/hr, EPR 0.79). The voice recorder has Shut them off at 10:02:03.5, fourteen seconds before the levers start moving.' },
      { v: 'The reduction is symmetric, which rules out damage', who: 'Computed here from the NTSB tabulation', src: 'derived',
        weight: 'Across 80 paired EPR samples the left-right difference has a maximum of 0.062 and a mean of 0.007. N1 left and right stay within two per cent throughout the retardation. Fuel flows track. That is two levers moved together by a hand, not an engine failing.' },
    ],
    reading: 'The hijackers did not shut the engines down, and on a 757 they may not have known how: the fuel control switches were never moved. What they did was close both thrust levers, and the voice recorder carries the order fourteen seconds before the parameters move. One further detail is recorded and not explained. At 10:02:17.3 a native English speaking male shouts Turn it up, and 10:02:17 is the exact second the thrust begins coming back instead. That is a coincidence of timing on a one-second grid, not proof of anything, and it is set down here as an observation rather than a conclusion.',
    appSays: 'The app states that both engines ran to impact, that thrust was commanded to idle from about 10:02:17, and that the reduction was symmetric. A small anomaly is left standing rather than smoothed: in the last two samples, 10:03:07 to 10:03:09, left EPR rises to 0.818 and left N1 to 58 while the right stays at 0.756. Impact effects, a sensor artefact and a final lever movement are all candidates and the record does not choose between them.',
  },
  {
    id: 'ua93-impact-attitude',
    subject: 'United 93 impact attitude: which document actually says inverted?',
    tags: ['DATA', 'CRASH'],
    status: 'resolved',
    why: 'The attitude at impact is the strongest physical evidence the shootdown claim has, because an uncommanded roll to inverted is what asymmetric damage produces. A fact doing that much work needs a source, and this app has been asserting one it has not checked.',
    readings: [
      { v: 'Rolled right and pitched nose-down in response to flight control inputs', who: 'NTSB Flight Path Study, 12 Feb 2002', src: 'ntsb',
        weight: 'This wording is confirmed. It attributes the manoeuvre to the controls but does not by itself state a roll angle at impact.' },
      { v: '40 degrees nose-down and inverted', who: 'Attributed in this app to the NTSB', src: 'ntsb',
        weight: 'Unverified. The figures may come from the 9/11 Commission, from the animation prepared for the Moussaoui trial, or from the study itself. Nobody here has confirmed which.' },
    ],
    reading: 'Settled, in favour of the app. ROLL ANGLE and PITCH ANGLE are both recorded parameters in the NTSB tabulation for DCA01MA065. Roll passes 90 degrees at 10:03:03 and peaks at 161.4 degrees at 10:03:07; pitch reaches minus 41.1 degrees at 10:03:09, the last recorded sample. Inverted and 40 degrees nose-down are measurements, not inferences. Original wording of this entry doubted the NTSB badge; that doubt is withdrawn.',
    appSays: 'The app states 40 degrees nose-down and inverted in three places and badges all three NTSB. That badge is provisional pending a check of the Flight Path Study text, and of whether any roll-attitude trace was ever published for the final ninety seconds.',
  },
  {
    id: 'ua93-tail-and-apu',
    subject: 'Was the tail hit, and did the APU give a heat-seeker anything to aim at?',
    tags: ['DATA', 'FDR', 'STEELMAN'],
    status: 'resolved',
    why: 'Two variants of the missile claim aim a heat-seeking missile at the auxiliary power unit, one at its exhaust and one at its door, and both put the damage at the tail. The recorder carries channels for the unit, the stabiliser and the yaw dampers, and they had not been read.',
    readings: [
      { v: 'The APU was off and cold for the whole recorded flight', who: 'NTSB DCA01MA065 tabulation, DCA01MA065_tabAtoE.csv, read directly', src: 'ntsb',
        weight: 'APU RPM reads 0.0 per cent on all 79 samples, 08:39:42 to 10:02:54, a span that includes the claimed intercept time of 09:58. APU EGT reads 6 to 8 deg C on all 79: 8 deg C from 08:50:18 to 08:57:46 and 6 deg C otherwise, the last at 10:02:50. APU BUS AC VOLTS reads 2.5 VAC on all 79. APU FIRE reads NORMAL on all 5,050 samples to 10:03:09 and APU FAULT reads OK on all 1,263 to 10:03:08. APU LOW OIL QUANT, APU BLEED VALVE and APU GEN APB OPEN are normal throughout. All eight are on Attachment I-1, Parameters Validated. AFT CARGO FIRE reads NORMAL on all 5,050 samples to 10:03:09. The file read is the copy in the Internet Archive item NTSB_FOIA_Appeal_2012-00001-A_Nov_10_2011, SHA-256 fe09bdbdc5dafb1f724fa9603af3641da45f8c3c83062f093eb88c3c39639fb0.' },
      { v: 'The tail channels show no damage', who: 'The same tabulation, validated channels', src: 'ntsb',
        weight: 'UNSCHED STAB MOVE, validated on Attachment I-6, reads NORMAL on all 1,262 samples to 10:03:06. STAB POSITION, four channels, validated on I-6, holds between minus 3.65 and minus 2.33 degrees from 09:55, with a largest one-second change of 0.39 degrees and a last reading of minus 2.59. STAB TRIM FAULT and STAB TRIM MODULE, validated on I-6, read OK. YAW DAMPER - L, YAW DAMPER - R and YAW DAMPER MODULE, validated on I-7, read OK throughout. HYD SYS LO PRESS C, L and R read normal to 10:03:08 and 10:03:09.' },
      { v: 'The unit channels are published once every 64 seconds', who: 'Computed here from the same tabulation', src: 'derived',
        weight: 'APU RPM and APU EGT are sampled once every 64 seconds in the tabulation. A start and stop falling between two samples would not show on RPM, and the last RPM and EGT samples, at 10:02:54 and 10:02:50, are 17 and 21 seconds before impact. The discretes run closer to the end: APU FIRE to 10:03:09 and APU FAULT to 10:03:08. What 79 consecutive readings of zero RPM and 6 to 8 deg C do establish is that the unit was not running at any sample from 08:39:42 to 10:02:54.' },
      { v: 'There is no APU door channel for this aircraft', who: 'NTSB DCA01MA065, Attachment IV, the data frame layout for this airframe', src: 'ntsb',
        weight: 'APU DOOR does not appear in the frame this recorder wrote. It exists only in United\'s generic 757-3b database. The door cannot be read either way, so the door variant is tested on the unit itself: an open door on a unit at zero RPM and 6 to 8 deg C exposes nothing hot.' },
      { v: 'Channels on the not-working list, and not used', who: 'NTSB DCA01MA065, Attachments I-8 and I-10', src: 'ntsb',
        weight: 'APU BUS FREQ, APU LOAD and APU OIL LEVEL are on Attachment I-8. YAW DAMPER ENGAGE L and R are on I-10, and they are the only yaw damper channels on the list. Nothing in this entry rests on any of them.' },
    ],
    reading: 'The auxiliary power unit was off and cold from the first sample to the last: zero RPM, an exhaust temperature of 6 to 8 deg C, and no fire, fault, oil or bleed indication. It gave a heat-seeker nothing to aim at, so the variant aimed at its exhaust and the variant aimed at its door both fail on the recorder. The tail channels agree: no unscheduled stabiliser movement, a steady stabiliser, no trim fault, yaw dampers reading OK, and all three hydraulic systems above their low-pressure trip to 10:03:08. The limits are stated with the readings: RPM and EGT are published once every 64 seconds and end 17 and 21 seconds before impact, and there is no door channel for this airframe.',
    appSays: 'The app states that the APU was off and cold throughout, with the sample counts and the 64-second sampling, that no APU door channel exists for this airframe, and that the recorded tail channels show no damage. It does not use the three APU channels or the two yaw damper engage channels on the not-working list.',
    refs: ['UA93', 'NTSB_TAB_IA'],
  },
  {
    id: 'ua93-warnings',
    subject: 'Every warning United 93 raised, and what raised it',
    tags: ['DATA', 'FDR', 'CVR'],
    status: 'flagged',
    why: 'The voice recorder carries five sets of alert tones, four stretches of a warning and a loud air noise. A tone near the claimed intercept time with nothing on the aircraft to explain it would matter, so each one was matched against the flight data channels that could have raised it. One set of tones has no match.',
    readings: [
      { v: 'The warning channels on the flight data recorder', who: 'NTSB DCA01MA065 tabulation, validated channels, read directly', src: 'ntsb',
        weight: 'COMPUTED AIRSPEED is 293 kt [[knots]] at 09:58:00, then rises every second from 338 kt at 10:02:28 to 487.5 kt at 10:03:09. OVERSPEED is on from 09:44:37 to 09:45:40 and from 10:02:39 to 10:03:09. MASTER WARNING, captain and first officer, is on at 09:34:13 to 09:34:36, 09:44:36 to 09:44:40, 09:46:36 to 09:46:42 and 10:00:29 to 10:03:09. The autopilot disconnect channels, A/P WARN-2, are on at 09:34:13 to 09:34:37, 09:46:37 to 09:46:43 and 10:00:29 to 10:03:09, and normal between. MASTER CAUTION LIGHT, sampled every 4 seconds, is on at 09:28:20 to 09:29:16, 09:46:04 to 09:46:12, 10:00:00 to 10:00:08 and 10:02:32. The selected altitude is 4,992 ft from 09:48:32.' },
      { v: 'The tones and warnings on the voice recorder', who: 'FBI transcript of the cockpit voice recorder', src: 'commission',
        weight: 'Alert tones at 09:45:42.3 (four), 09:46:03.2 (four), 09:59:57.8 (three), 10:02:32.1 (four) and 10:03:05.5 (four). What the transcriber calls an "auto-pilot disconnect warning" runs from 09:34:14 to 09:34:38, from 09:44:37 to 09:45:42.1, from 09:46:37 to 09:46:44, and from 10:00:30.2 to the end. "A loud air noise" starts at 10:02:43.1, stops at 10:02:52.2, starts again at 10:02:53.4, and stops with screams at 10:03:09.2.' },
      { v: 'The transcript most likely misnames the overspeed warning', who: 'Computed here, recorder against transcript', src: 'derived',
        weight: 'The transcribed autopilot disconnect warning from 09:44:37 to 09:45:42 matches OVERSPEED, on from 09:44:37 to 09:45:40, to the second, and the autopilot disconnect channels read normal across that minute. The other three transcribed stretches match A/P WARN-2.' },
      { v: 'Three sets of tones match the master caution light', who: 'Computed here', src: 'derived',
        weight: 'The tones at 09:46:03.2, 09:59:57.8 and 10:02:32.1 fall with the master caution light coming on at 09:46:04, 10:00:00 and 10:02:32, allowing for the light being sampled every 4 seconds.' },
      { v: 'Two sets follow the aircraft leaving its selected altitude, on timing only', who: 'Computed here', src: 'derived',
        weight: 'The tones at 09:59:57.8 and 10:03:05.5 each come about two seconds after the aircraft moved more than 300 ft off the selected 4,992 ft: at 09:59:56 at 5,317 ft, and at 10:03:04 at 4,552 ft. No crossing back inside 300 ft produced a tone. No altitude alert channel is recorded, so this is a match on timing and nothing more.' },
      { v: 'The air noise follows airspeed', who: 'Computed here', src: 'derived',
        weight: 'It begins at 10:02:43.1, four seconds after OVERSPEED trips at 10:02:39, as airspeed passes 360 kt, and it grows as airspeed grows. None is noted in the 4 minutes 43 seconds after the claimed intercept time of 09:58.' },
      { v: 'Both air-conditioning packs went off within about four seconds of the first "Cut off the oxygen!"', who: 'Computed here, recorder against transcript', src: 'derived',
        weight: 'CAM-1 has "Cut off the oxygen!" at 10:01:16.9 and "Cut off the oxygen! Cut off the oxygen! Cut off the! oxygen" at 10:01:18.7, both marked mixed: an Arabic sentence containing an English technical word. ECS PACK ON/OFF LEFT and RIGHT read on until 10:01:17 and off from 10:01:21 to the end, and pack overheat reads normal throughout. A loud metallic click is transcribed at 10:01:23.8. The recorder does not show who moved the switches. The aircraft was below 10,000 ft, where shutting the packs stops fresh air coming in but cannot deprive anyone of breathable air.' },
      { v: 'No fire, smoke, terrain or windshear warning at any point', who: 'NTSB DCA01MA065 tabulation', src: 'ntsb',
        weight: 'Every fire and smoke channel reads normal, and neither fire extinguisher switch is ever pulled. Every ground-proximity, terrain and windshear channel reads false throughout. CABIN ALT > 10kft reads normal. PASS OXY ON reads off on all 79 samples.' },
      { v: 'Two validated channels read what cannot be true', who: 'The same tabulation', src: 'ntsb',
        weight: 'AC BUS OFF L and R read BUS OFF on every sample from 08:39:09, and R ENG BLEED OVHT reads OVHT on every sample from 08:39:43. Both are on the validated list. Both are impossible as literal readings, AC BUS OFF most plainly because the recorder itself runs on AC power, so the labels are inverted or the channels are stuck. They are evidence of nothing, and nothing here uses them.' },
      { v: 'The four tones at 09:45:42.3 are unexplained', who: 'Computed here', src: 'derived',
        weight: 'They sound at 19,271 ft, with the master caution light off on the samples either side, and no channel read here accounts for them.' },
    ],
    reading: 'Every tone and warning on the tape except one set of tones has a recorded match. The overspeed warning, which the transcript most likely misnames, the master caution light, the autopilot disconnect and, on timing alone, an altitude alert account for the rest, and the air noise tracks airspeed in the final dive. None of these warnings is on at the claimed intercept time of 09:58, and no fire, smoke, terrain or windshear channel ever trips. Both packs went off within about four seconds of the first "Cut off the oxygen!", and the recorder does not show who moved the switches. AC BUS OFF and R ENG BLEED OVHT read impossible values from the first samples and are set aside. The four tones at 09:45:42.3 stay unexplained, and the entry stays flagged until something accounts for them.',
    appSays: 'The app lists each tone and warning beside the channel it matches, says the transcript most likely calls the overspeed warning an autopilot disconnect, gives the altitude alert match as timing only, states that both packs went off within about four seconds of the first "Cut off the oxygen!" without saying who moved the switches, sets aside AC BUS OFF and R ENG BLEED OVHT, and leaves the tones at 09:45:42.3 unexplained.',
    refs: ['UA93', 'NTSB_TAB_IA'],
  },
  {
    id: 'gibney-eastbound-record',
    subject: 'Rick Gibney: the first record of the flight itself',
    tags: ['GIBNEY'],
    status: 'open',
    why: 'Until now every detail of the Jacoby flight came from press accounts and from Gibney himself, and no retrieved source gave a time for any leg. Two FAA records at the National Archives now document the eastbound leg with times. They settle where it started and when it was flown, and they say nothing about the morning, which is the part the claim depends on.',
    readings: [
      { v: 'An F-16, NODAK99, route beginning Bozeman, held by Toronto Centre at 21:39Z', who: 'FAA, Boston ARTCC flight-data message file 5 ZBW 70 FD SEPT 11 TRASH.TXT, National Archives NAID 7599510, Record Group 237', src: 'foia',
        weight: 'Message header "112139 CZYZZGZT": Toronto Centre, 11 September, 21:39Z, which is 17:39 EDT. Text: "FP NODAK99 F16/I 6020 500 YYZ P2220 280 BZN./.YYZ..ALB". Read as an F-16 under callsign NODAK99, filed true airspeed 500 kt, estimated over Toronto at 22:20Z at 28,000 ft, on a route from BZN, Bozeman, through Toronto to Albany. The same file has a second message, header "112336 KBTVYFYX", text "FP NODAC99 F16/I 480 ALB P2350 310 ALB..ACY..LFI/0100": the onward flight from Albany to Langley AFB via Atlantic City, proposed for 23:50Z, 19:50 EDT.' },
      { v: 'Both callsigns on the Albany approach strips', who: 'FAA, Albany TRACON flight strips, 5 ALB 7 Flight Strips ALB TRACON 91101.pdf, page 12, National Archives NAID 7601591', src: 'foia',
        weight: 'Strip: "NODAK99, 3436, A2249, F16/I, RKA 049/037, ALB", arriving Albany at 22:49Z, 18:49 EDT. Strip: "NODAC99, 3461, ALB, F16/I, P2350, 310, ALB ACY LFI", proposed out of Albany for Langley at 23:50Z.' },
      { v: 'Gibney returned Jacoby to Albany on 11 September, then flew on to Langley', who: 'David Somdahl, North Dakota House Journal, 60th Legislative Assembly, 16 January 2007', src: 'press',
        weight: '"Another 119th Fighter Wing F-16 was dispatched to meet an urgent need to return the Emergency Management Director for the State of New York from a national conference being held at Big Sky resort in Montana. 119th Operations Group Commander, Lt. Col. Rick Gibney, returned Mr. Edward Jacoby to Albany on Sept. 11th, then flew on to the Langley Alert Detachment for duty." It gives no times.' },
      { v: 'The records do not name the pilot, and they match every account of his flight', who: 'Computed here', src: 'derived',
        weight: 'Neither record names the pilot or settles the tail number. The type, the date, the route and the onward leg to Langley agree with the House Journal and with every press account of the flight. InForum in 2011 names Missoula as the Montana airport; the flight plan route begins at BZN.' },
      { v: 'Times derived from the filed speed', who: 'Computed here, no wind', src: 'derived',
        weight: 'Toronto to Albany is 300 miles, about 31 minutes at 500 kt, which agrees with the 22:49Z arrival. Bozeman to Toronto is 1,544 miles, about 161 minutes, which puts the Bozeman departure near 19:39Z, 15:39 EDT. Time spent refuelling moves that earlier; a tailwind moves it later. On the same basis the aircraft was over Fargo about 20:49Z, 16:49 EDT, before any time spent refuelling. No record times the refuelling, and the 21:39Z message puts it before 17:39 EDT.' },
      { v: 'What the records settle and what they do not', who: 'Computed here', src: 'derived',
        weight: 'Settled: the Montana airport was Bozeman, the eastbound leg was flown in the afternoon, and the onward Langley leg happened. Not settled: the tasking time, the departure from Fargo, the arrival at Bozeman and the tail number.' },
      { v: 'They do not rule out the itinerary the claim needs', who: 'Computed here', src: 'derived',
        weight: 'The claim has the F-16 fly Fargo, Shanksville, Bozeman, Albany. Shanksville to Bozeman is 1,667 miles, under three hours at cruise, which leaves time before a mid-afternoon departure from Bozeman. The eastbound record is consistent with that as well as with the accounts. What would decide it is when the F-16 landed at Bozeman.' },
    ],
    reading: 'The eastbound leg is now on an FAA record with times, and it was flown in the afternoon: a Bozeman departure near 15:39 EDT on the filed speed, Toronto Centre holding the plan by 17:39 EDT, Albany at 18:49 EDT, and a plan on to Langley for 19:50 EDT. None of it reaches the morning. The records fit the press accounts, and they also fit the claim, which needs the F-16 over Shanksville at 09:58 and at Bozeman by mid-afternoon. When the F-16 landed at Bozeman is now the deciding unknown, and no retrieved record gives it. The entry stays open for that reason.',
    appSays: 'The app cites both FAA records and the House Journal for the eastbound leg, gives its times as derived from the filed speed with no wind, and states what the records settle and what they leave open, including that they do not rule out the claimed itinerary.',
    refs: ['NARA_FAA_NODAK', 'ND_HOUSE_2007', 'GIBNEY'],
  },
  {
    id: 'bozeman-albany-nonstop',
    subject: 'Was Bozeman to Albany flown without a fuel stop?',
    tags: ['GIBNEY'],
    status: 'open',
    why: 'The whole fuel finding rests on that leg being one leg. If he landed for fuel or refuelled in the air, the leg length proves nothing about the tanks [[dropTanks]], though the tanks would still be likely, and the Bozeman kinematics would be unchanged.',
    readings: [
      { v: 'One flight plan, Bozeman to Albany through Toronto, with no other airport named', who: 'FAA flight-data message and Albany TRACON strips, National Archives NAIDs 7599510 and 7601591', src: 'foia', weight: 'NODAK99, route "BZN./.YYZ..ALB", estimated over Toronto at 22:20Z and arriving Albany at 22:49Z. A flight plan is not a fuel record: it neither shows nor excludes a tanker. See gibney-eastbound-record.' },
      { v: 'Refuelled in the air roughly above Fargo', who: 'Dave Roepke, "Unforgettable day", The Forum of Fargo-Moorhead, 25 August 2011', src: 'press', weight: '"Refueling in-air roughly above Fargo, Gibney and Jacoby flew back east." This is the only retrieved source for a refuelling. The Popular Mechanics page this app links has no refuelling text, and the Somdahl quote the app took from it does not mention one. No record times the refuelling or names a tanker.' },
      { v: 'Two landings: Bozeman to collect Jacoby, Albany to deliver him', who: 'Press accounts of the mission', src: 'press', weight: 'No ground fuel stop is mentioned in any retrieved account. This app modelled the flight as a single leg.' },
      { v: 'Routing over Fargo costs almost nothing', who: 'Computed here', src: 'derived', weight: 'Fargo lies 56 miles north of the Bozeman-Albany great circle, 685 miles along its 1,843. Passing over Fargo adds about 6 miles, 0.3 per cent, if the flight still went by Toronto as filed, and only a few miles if it flew from Fargo straight to Albany. Grand Forks AFB, a KC-135 base, is 76 miles from Fargo. On the filed speed and no wind the aircraft was over Fargo about 20:49Z, 16:49 EDT, before any time spent refuelling, and the 21:39Z Toronto Centre message puts the refuelling before 17:39 EDT.' },
      { v: 'With one refuelling over Fargo, the tanks are inferred, not established', who: 'Computed here', src: 'derived', weight: 'Bozeman to Fargo, 687 miles, is 0.69 of a clean two-seat F-16\'s range on this app\'s figure of 996 miles and 0.84 on the USAF figure of 814. Fargo to Albany, 1,159 miles, is 1.16 and 1.42 of the same two figures. So tanks remain likely, but only if there was a single refuelling, and no record documents one. The flight plan gives the type only as F16/I, so the model is not recorded either.' },
      { v: 'A fuel stop is plausible', who: 'Arithmetic done here', src: 'derived', weight: '1,843 miles is about 82% of a tanked two-seater\u2019s ferry range [[ferryRange]], and InForum reported in 2019 that he asked to fly at lower altitudes to ease stress on Jacoby, which burns more fuel.' },
    ],
    reading: 'Unresolved, but the question has narrowed. No retrieved account mentions a ground stop, and the FAA flight plan names no airport between Bozeman and Albany. One source, InForum in 2011, reports a refuelling in the air roughly above Fargo, and routing over Fargo adds 6 miles. If that refuelling happened, the flight was two legs for fuel, and the tanks are inferred from the longer half rather than established by the whole. It does not help the claim either way: a refuelling adds time rather than saving it, and the Montana-route conclusion of roughly Mach 2.9 [[mach]] stands because it exceeds even a clean jet\'s Mach 2.0.',
    appSays: 'The app states the reported refuelling over Fargo with InForum 2011 as its only source, marks the tanks as inferred rather than established, likely on a single refuelling that no record documents, and describes the aircraft as a two-seat F-16 without asserting the D model. The Montana-route finding is unchanged.',
    refs: ['GIBNEY', 'F16', 'INFORUM_2011', 'NARA_FAA_NODAK'],
  },
  {
    id: 'pentagon-second',
    subject: 'The Pentagon impact: 09:37:45 or 09:37:46?',
    tags: ['DATA'],
    status: 'resolved',
    why: 'It changes nothing. Recorded so the app\'s own timestamps can be checked to the second.',
    readings: [
      { v: '09:37:46', who: '9/11 Commission Report', src: 'commission', weight: 'The figure this app used until now, and the one most often quoted.' },
      { v: '09:37:45', who: 'NTSB Flight Path Study, American 77', src: 'ntsb', weight: 'From the recorder [[fdr]]. The last FDR subframe.' },
    ],
    reading: 'One second, between two primary sources that agree on everything else. The recorder is the closer instrument, so the app now uses 09:37:45 everywhere, including GOFER 06\'s track, where the C-130 crew watched it happen. The difference is recorded here rather than silently reconciled.',
    appSays: 'The app uses 09:37:45. The Commission gives 09:37:46, one second later, from a coarser instrument.',
    refs: ['COMMISSION', 'AA77'],
  },
  {
    id: 'gofer-track-fixed',
    subject: 'GOFER 06: the track that manufactured a contact',
    tags: ['GOFER'],
    status: 'resolved',
    why: 'The app drew an unarmed C-130 passing within three miles of United 93. That is inside the AIM-9 [[sidewinder]] ring the app draws, so the app itself was showing a contact that did not happen.',
    readings: [
      { v: '"About 30 miles", his own radio call at 10:06', who: 'ATC transcript', src: 'commission', weight: 'Contemporaneous. The figure now plotted.' },
      { v: '~34 nautical miles southeast', who: 'Miles Kara, radar reconstruction', src: 'press', weight: 'Instrument-derived, and consistent with the radio call.' },
      { v: '~3 miles', who: 'This app, until corrected', src: 'derived', weight: 'Traced from secondary retellings. Wrong, and in the direction that suggests a contact.' },
    ],
    reading: 'Three errors in one track: a 09:30 departure against the 1333Z on the Andrews tower strips, a westward continuation as though he reached Minnesota, and a closest approach of three miles.',
    appSays: 'Corrected. Departure 09:33, diversion and landing at Youngstown, Ohio, and a closest approach to United 93 of 38 miles, 3.4x outside the AIM-9 ring. The false contact is gone.',
    refs: ['GOFER', 'KARA_NEADS'],
  },
  {
    id: 'airfone-rows',
    subject: 'Airfone installation: nine rows, or twelve?',
    tags: ['CALLS'],
    status: 'open',
    why: 'It bears on how many separate Airfone [[airfone]] handsets the 37 calls came from, which is what makes the call log hard to fabricate.',
    readings: [
      { v: 'Rows 23 to 34, twelve rows', who: 'The per-call row numbers in the NPS log', src: 'commission', weight: 'From billing records. The harder datum.' },
      { v: '"The last nine rows"', who: 'National Park Service summary, same page', src: 'commission', weight: 'A single source disagreeing with itself.' },
    ],
    reading: 'Nothing turns on it, but the summary sentence is looser than the data underneath it. The app follows the row numbers.',
  },
  {
    id: 'cell-count',
    subject: 'Cellular calls from United 93: two, or three?',
    tags: ['CALLS'],
    status: 'open',
    why: 'The cellular count is the target of the Faraday-cage argument.',
    readings: [
      { v: 'Two: Edward Felt and CeeCee Lyles', who: 'FBI evidence, Moussaoui sentencing trial', src: 'commission', weight: 'Carrier records. The figure the app uses.' },
      { v: 'Three: the above plus Andrew "Sonny" Garcia', who: 'NPS call log', src: 'commission', weight: 'Unknown time, a single word before disconnect.' },
    ],
    reading: 'Probably connected-versus-attempted, since an incomplete call would not reach a billing total. That is a guess and is labelled as one. The argument is unaffected either way.',
  },
  {
    id: 'cell-success-rate',
    subject: 'Air-to-ground cell call success rate in 2001',
    tags: ['CALLS', 'DATA'],
    status: 'open',
    why: 'A percentage here would be the most quotable number in the dispute, so it must not be invented.',
    readings: [
      { v: 'No measured rate exists that can be quoted', who: 'Searched and not found', src: 'derived', weight: 'NASA-era work covers avionics interference, not call completion. The 2004 Qualcomm test used an onboard picocell, the opposite mechanism.' },
      { v: '~1% at 20,000 ft, 0% at 7,000 ft in a twin', who: 'A. K. Dewdney, Project Achilles', src: 'claim', weight: 'The only figure in circulation. Advocacy source, small sample, light aircraft rather than airliners.' },
    ],
    reading: 'The qualitative claim stands on engineering grounds: downtilted antennas, handover built for road speeds, too many cells visible at altitude. The quantitative one does not. The app does not quote the number.',
  },
  {
    id: 'fuel-yardstick',
    subject: 'Fuel as a constraint on the Pennsylvania leg: this app overstated it',
    tags: ['CLAIM', 'DATA'],
    status: 'resolved',
    why: 'Fuel was presented as the constraint that closed the claim. It is not, and the error favoured the app\'s own argument.',
    readings: [
      { v: 'Ferry range with external tanks is about 2,450 miles, one way. Fargo to Somerset County is 1,012, roughly 41% of it.', who: 'Published F-16 figures with 2 x 370 gal wing tanks and a 300 gal centreline', src: 'press', weight: 'The right yardstick for a one-way transit. An ordinary leg for a tanked fighter.' },
      { v: 'Unrefuelled combat radius is about 340 miles, so Somerset County is 3.0x it and "never enters it, however long you wait".', who: 'This app, until corrected', src: 'derived', weight: 'True of a combat radius [[combatRadius]] (out, fight, and back) and the wrong measure for the leg claimed.' },
      { v: 'The full itinerary is 4,522 miles, about 1.85x maximum ferry range.', who: 'Computed here', src: 'derived', weight: 'This part survives: the whole day needs at least one refuelling stop.' },
    ],
    reading: 'Fuel does not rule out the flight to Pennsylvania. It only rules out doing the entire claimed itinerary without refuelling, and refuelling is possible, though a tanker rendezvous leaves scheduling and crew records. The load-bearing arguments are the geometric and evidentiary ones: a 22-mile engagement zone [[wez]] at one instant, NEADS [[neads]] not knowing United 93 existed until 10:07, no order having reached any pilot, and the unit and passenger placing him over Montana.',
    appSays: 'Corrected twice. First the map drew both rings instead of only the restrictive one. Then the combat-radius ring was removed altogether, because a combat radius presumes no external tanks [[dropTanks]] and the documented Montana-to-Albany leg implies the tanks were fitted (with the one reported refuelling over Fargo, its Fargo-to-Albany piece of 1,159 miles is beyond a clean two-seat F-16), so it was a limit for a configuration the record makes unlikely. What remains is ferry range [[ferryRange]] with tanks and its half-radius. The fastest speed band also dropped from Mach 2.0 (a clean-configuration number, now marked unavailable for the same reason) to Mach 1.6, the placarded limit [[placard]] with tanks. A related overclaim, that tanks would preclude carrying Sidewinders [[sidewinder]], was never made and would have been wrong: tanks sit on the wing and centreline stations, Sidewinders on the wingtip rails.',
    refs: ['F16', 'GIBNEY'],
  },
  {
    id: 'critic-substance',
    subject: 'DIRNSA CRITIC 1-2001: the substance of all four messages',
    tags: ['CRITIC'],
    status: 'withheld',
    why: 'The CRITIC [[critic]] is the record of what national leadership was told, as against what was happening. The app can draw the second half of that comparison minute by minute. The first half is redacted.',
    readings: [
      { v: 'Four messages, identified by DTG, acknowledged by NSA, released with the substance removed', who: 'NSA FOIA release', src: 'foia', weight: 'The existence, timing and numbering [[dtg]] are not in dispute. Only the content is missing.' },
      { v: 'Withheld as "OGA" material because NORAD, as a bi-national command, is not subject to FOIA', who: 'NSA\'s stated ground for withholding', src: 'foia', weight: 'A basis [[oga]] contested by the pending request [[foia]], which argues a record in NSA\'s own files is an agency record regardless of who wrote it.' },
      { v: 'A phantom "Boeing 767 originating from JFK" and confusion over Flight 77', who: 'The fragments that survived redaction', src: 'foia', weight: 'The only content visible. Both fragments are errors.' },
    ],
    reading: 'This is a gap rather than a disagreement between sources. The two fragments that survived redaction are both wrong, which is why the full text matters.',
    appSays: 'The four DTGs are on the timeline as first-class events with their content marked withheld. Nothing is invented to fill them.',
    refs: ['KARA_CRITIC', 'MUCKROCK'],
  },
  {
    id: 'critic-addressees',
    subject: 'CRITIC distribution: who was told, and when',
    tags: ['CRITIC'],
    status: 'withheld',
    why: 'A CRITIC exists to reach the President within minutes. Whether it did, and when, is what the request asks.',
    readings: [
      { v: 'TO and INFO addressees, routing indicators, delivery and acknowledgment time-stamps, all withheld', who: 'NSA FOIA release', src: 'foia', weight: 'Requested under item (f) of the pending request.' },
      { v: 'The White House Situation Room, NMCC and the NOIWON community are where a CRITIC is designed to land', who: 'CRITIC system design under NSCID No. 7', src: 'press', weight: 'Inference from design, not from disclosure.' },
    ],
    reading: 'The app draws the onward links, dashed. Solid lines would assert what the request is trying to establish.',
    appSays: 'NORAD [[norad]] to NSA is drawn solid because that hop is documented. Everything past NSA is dashed and labelled as inferred.',
    refs: ['KARA_CRITIC', 'MANEKI'],
  },
  {
    id: 'critic-phantom-767',
    subject: 'The "Boeing 767 originating from JFK"',
    tags: ['CRITIC', 'DATA'],
    status: 'open',
    why: 'The highest-precedence warning channel in the US government carried a report of an aircraft that did not exist.',
    readings: [
      { v: 'A report of a Boeing 767 from JFK heading for Washington', who: 'Visible in the redacted CRITIC release', src: 'foia', weight: 'Fragment. No surrounding context survives.' },
      { v: 'No such flight existed', who: 'The four hijacked aircraft are fully accounted for', src: 'commission', weight: 'Certain.' },
    ],
    reading: 'The fragment does not show where the phantom came from. One candidate is a garbled relay of American 11, which was reported still airborne and heading for Washington long after it had struck the North Tower. The full text would settle it.',
    refs: ['KARA_CRITIC', 'COMMISSION'],
  },
  {
    id: 'neads-first-notice',
    subject: 'When NEADS first heard of United 93',
    tags: ['UA93', 'DATA'],
    status: 'resolved',
    why: 'If NEADS [[neads]] knew of United 93 at 09:16, fighters could have been directed at it. If it knew at 10:07, the aircraft was down before the sector heard its name.',
    readings: [
      { v: '10:07', who: 'NEADS tapes and the 9/11 Commission Report', src: 'commission', weight: 'The sector\'s own recordings, time-stamped. Cleveland Center told NEADS of United 93 at 10:07, four minutes after impact.' },
      { v: '09:16', who: 'NORAD testimony to the Commission, May 2003 (Gen. Arnold, Col. Scott)', src: 'press', weight: 'Given in public testimony, and contradicted by the tapes.' },
    ],
    reading: 'The Commission found the May 2003 testimony inaccurate against the tapes, and its staff considered referring the matter for investigation. 10:07 is the figure the tapes support.',
    appSays: 'The app uses 10:07 for NEADS\'s first notice of United 93 and treats the earlier testimony as superseded.',
    refs: ['COMMISSION', 'KARA_NEADS', 'NEADS_FILES'],
  },
  {
    id: 'shootdown-authority-time',
    subject: 'When shootdown authority was given',
    tags: ['UA93', 'CLAIM'],
    status: 'open',
    why: 'The claim needs an order in existence by 09:58. Every account of the authorisation places it after United 93 was down, but the accounts disagree by minutes and the record is thin.',
    readings: [
      { v: 'Between about 10:10 and 10:18', who: '9/11 Commission Report', src: 'commission', weight: 'The Commission found no documentary record of the call between the Vice President and the President in which the authority was given, and placed it in this window from Situation Room logs and witness accounts.' },
      { v: 'Earlier, before United 93 was down', who: 'Richard Clarke\'s account of the crisis videoconference; Norman Mineta\'s testimony about the Presidential Emergency Operations Center', src: 'press', weight: 'Both place the discussion of authority earlier in the morning. The Commission did not adopt the earlier timing.' },
      { v: '10:10 in the timeline; about 10:18 in the awareness map', who: 'This app', src: 'derived', weight: 'The two ends of the Commission\'s window, used in different places.' },
    ],
    reading: 'Unsettled to the minute, and the Commission said so. Every reading places the authority after 10:03:11. The fixed point is 10:31, when NEADS [[neads]] received it and did not pass it to its pilots.',
    appSays: 'The app now says "the earliest documented authorisation is about 10:10" everywhere and treats 10:31 at NEADS as the hard fact.',
    refs: ['COMMISSION'],
  },
  {
    id: 'felt-call',
    subject: 'Edward Felt\'s 911 call: was an explosion reported?',
    tags: ['UA93', 'CALLS'],
    status: 'open',
    why: 'This is the one call from the aircraft in which a witness is said to have reported an explosion and smoke, which is why it circulates as evidence of a missile.',
    readings: [
      { v: 'No explosion or smoke on the recording', who: 'FBI; the recording as entered at the Moussaoui sentencing trial', src: 'commission', weight: 'The recording exists. Felt reports a hijacking from a rear lavatory, and the call ends.' },
      { v: 'Felt reported an explosion and white smoke', who: 'Dispatcher Glenn Cramer\'s initial account to reporters, 11 September 2001', src: 'press', weight: 'Reported on the day by the supervisor who took the call. The detail does not appear on the recording.' },
    ],
    reading: 'A same-day recollection against a recording. The recording carries more weight, but the two sources conflict and the entry stays open so the disagreement is on the record.',
    appSays: 'The app lists the call at 09:58, about 5,000 ft, one of two cellular calls, with no explosion reported.',
    refs: ['COMMISSION', 'UA93'],
  },
  {
    id: 'delta-1989',
    subject: 'Delta 1989: the aircraft NEADS was tracking over Ohio',
    tags: ['UA93', 'DATA'],
    status: 'resolved',
    why: 'Accounts of NEADS "tracking a hijack over Ohio" from about 09:41 are sometimes read as NEADS tracking United 93. It was tracking a different aircraft.',
    readings: [
      { v: 'Delta 1989, a Boeing 767 out of Boston, wrongly suspected of hijacking; NEADS tracked it from about 09:41 and it landed safely at Cleveland', who: '9/11 Commission Report and the NEADS tapes', src: 'commission', weight: 'Named on the tapes by flight number. NEADS had a radar track on it.' },
      { v: 'NEADS was watching United 93 in that airspace', who: 'Inference in some retellings', src: 'claim', weight: 'No United 93 track existed at NEADS before 10:07.' },
    ],
    reading: 'The sector was looking at Ohio airspace, at Delta 1989. It had no United 93 track. The two aircraft were in the same region during part of the same period, which is how the confusion arises.',
    appSays: 'The app does not draw Delta 1989. NEADS\'s first notice of United 93 stays at 10:07.',
    refs: ['COMMISSION', 'KARA_NEADS', 'NEADS_FILES'],
  },
  {
    id: 'rumsfeld-remark',
    subject: 'Rumsfeld\'s "shot down the plane over Pennsylvania"',
    tags: ['CLAIM'],
    status: 'flagged',
    why: 'The remark is quoted as an admission. It was made in a speech to troops in Baghdad on 24 December 2004, and the Pentagon called it a misstatement.',
    readings: [
      { v: '"...the people who attacked the United States in New York, shot down the plane over Pennsylvania and attacked the Pentagon..."', who: 'Donald Rumsfeld, Baghdad, 24 December 2004', src: 'press', weight: 'As spoken, in a list of the day\'s attacks. The subject of the sentence is the attackers.' },
      { v: 'A misstatement', who: 'Pentagon spokesman, the following week', src: 'press', weight: 'The official position, then and since, is that the passengers brought the aircraft down.' },
    ],
    reading: 'A slip in a list of the day\'s attacks; the sentence attributes the act to the attackers. Recorded here because it is widely quoted.',
    appSays: 'Not used as evidence either way.',
  },
  {
    id: 'second-aircraft',
    subject: 'Eyewitness reports of a second, smaller aircraft near the crash site',
    tags: ['UA93', 'WITNESS', 'CLAIM'],
    status: 'open',
    why: 'This is the eyewitness evidence the shootdown claim rests on. Several people near Shanksville described a small white jet close to the crash. Whether a documented aircraft accounts for those sightings decides whether the claim has a witness base.',
    readings: [
      { v: 'A Dassault Falcon 20 business jet, reported as a VF Corporation aircraft, was asked by air traffic control to descend and locate the crash site. Radar puts it circling at 6,000-6,500 ft between 10:11 and 10:15.',
        who: 'Miles Kara, radar reconstruction; co-pilot Yates Gladwell via Popular Mechanics',
        src: 'press',
        weight: 'Identified by type and operator, with a radar track and a named crew. It accounts for the sightings made after the explosion.' },
      { v: 'A small white jet passed low over the area at or just before the moment of impact.',
        who: 'Residents near Shanksville and Stoystown, in press accounts in the days after',
        src: 'press',
        weight: 'Same-week recollections, not instrument records. The Falcon does not cover these: it is over the site 8 to 12 minutes after impact, not before it.' },
      { v: 'The second aircraft was a fighter, and it fired on United 93.',
        who: 'The shootdown claim',
        src: 'claim',
        weight: 'No witness in these accounts describes a missile, a launch, or a fighter identified as one. The descriptions are of a small white jet, which is what the Falcon 20 is.' },
    ],
    reading: 'The sightings made after the explosion have a documented aircraft behind them. The sightings placed before impact do not, and no published radar reconstruction puts a second aircraft over the site at 10:03:11. Those accounts are unexplained by the record. Unexplained is not the same as corroborating: none of them describes a weapon, and the aircraft they describe is a small white jet rather than a fighter.',
    appSays: 'The app carries both the sightings and the Falcon 20 explanation. It draws no aircraft for the pre-impact sightings, because no aircraft has been identified for them.',
    refs: ['KARA_NEADS', 'COMMISSION', 'DEBRIS'],
  },
  {
    id: 'debris-spread',
    subject: 'Debris found miles from the crash site: wind, or a breakup in the air?',
    tags: ['UA93', 'WITNESS', 'CLAIM'],
    status: 'open',
    why: 'Light debris recovered a mile and more from the crater is the second pillar of the shootdown claim, on the argument that scattered wreckage is what a missile strike produces.',
    readings: [
      { v: 'Light material - paper, insulation, fabric - was lofted by the fireball and carried downwind. The wind that morning is reported as northwesterly at roughly 10 mph.',
        who: 'FBI statements at the time; Popular Mechanics',
        src: 'press',
        weight: 'Consistent with what was found at distance, which is light and wind-portable. Heavy structure, both recorders and the engine were recovered in and immediately around the crater.' },
      { v: 'Lightweight debris was recovered at Indian Lake, about 1.5 miles from the crater, and in smaller quantity near New Baltimore, reported at about 8 miles.',
        who: 'Contemporaneous reporting and local accounts',
        src: 'press',
        weight: 'The distances are reported rather than surveyed. The 8-mile figure comes from press accounts, not from a released recovery record.' },
      { v: 'A debris field that wide means the aircraft came apart before it hit the ground.',
        who: 'The shootdown claim',
        src: 'claim',
        weight: 'An in-flight breakup puts heavy structure away from the crater as well as light material. No heavy structure was recovered away from it.' },
    ],
    reading: 'The wind attribution is an explanation given at the time rather than a published study, and no debris-field survey with plotted find locations has been released. What can be checked is the kind of debris rather than the distance: everything recovered at a distance is light material. That is consistent with wind and not with a breakup in the air. The entry stays open because the survey that would settle it is not public.',
    appSays: 'The app plots no debris field. It carries the distance reports and the wind attribution as competing readings rather than choosing between them.',
    refs: ['DEBRIS', 'UA93'],
  },
  {
    id: 'steelman-premises',
    subject: 'STEELMAN: which of its granted conditions have no source',
    tags: ['CLAIM', 'DATA'],
    status: 'open',
    why: 'The steelman is only useful if a reader can tell which of its conditions are documented and which are handed to the claim by this app. Most of them are handed to it, and they are collected here so the list can be read in one place.',
    readings: [
      { v: 'Departure from Fargo at 08:46:40. No departure time from Fargo on 11 September 2001 has been published (FAA records time only the afternoon leg from Bozeman); the app uses the first impact as the earliest moment anyone had reason to act.',
        who: 'Assumption of this app', src: 'derived',
        weight: 'Granted. Any later departure makes the run faster and the claim harder.' },
      { v: 'Air-to-air missiles aboard. No record places AIM-9s [[sidewinder]] on any North Dakota Air National Guard F-16 that morning.',
        who: 'Assumption of this app', src: 'derived',
        weight: 'Granted. What the app has checked is only that tanks [[dropTanks]] and wingtip missiles can be carried together.' },
      { v: 'An intercept over Somerset County at 09:58. The time comes from the allegation, and it does not match the recorder, which puts impact at 10:03:11.',
        who: 'Donn de Grand-Pre, 2004', src: 'claim',
        weight: 'The app tests 09:58 because it is the more favourable of the two claimed times. See claim-time.' },
      { v: 'A cruise at 31,000 ft, a great-circle heading, no air-traffic routing, no weather and no time on the ground.',
        who: 'Construction of this app', src: 'derived',
        weight: 'Chosen to make the flying as easy as possible. All granted.' },
      { v: 'External tanks and the Montana-to-Albany leg.',
        who: 'Press accounts of the Jacoby mission, and Jacoby himself', src: 'press',
        weight: 'Inferred, not established. The one retrieved account of a refuelling puts it in the air roughly over Fargo, which leaves Fargo to Albany, 1,159 miles, beyond a clean two-seat F-16. The tanks follow only if that was the only refuelling, which no record documents, so the concession table lists fuel as granted.' },
    ],
    reading: 'Four of the five conditions above are assumptions rather than findings, and one is taken from the allegation being tested. None is concealed: each appears in the concession table with what it grants and what granting it costs. The point of listing them together is that a reader can see how much of the best case is construction.',
    appSays: 'Every granted condition is labelled in the concession table. Fuel is now marked as granted, an inference from the documented mission rather than an established fact; the rest are marked as granted, and the departure-time entry states that no departure time has been published.',
    refs: ['GIBNEY', 'CLAIMANT', 'F16'],
  },
);

export const STATUS_META = {
  resolved: { label: 'Resolved', tone: 'ok', blurb: 'The app follows the best-supported reading.' },
  todo:     { label: 'Known defect', tone: 'bad', blurb: 'The app still carries the weaker reading.' },
  open:     { label: 'Unsettled', tone: 'warn', blurb: 'Sources conflict; nothing available settles it.' },
  flagged:  { label: 'Internal oddity', tone: 'warn', blurb: 'A single source contradicts itself.' },
  withheld: { label: 'Withheld', tone: 'bad', blurb: 'Record acknowledged; substance redacted.' },
};

export const conflictsFor = (tag) => CONFLICTS.filter((c) => c.tags.includes(tag));
export const openCount = () => CONFLICTS.filter((c) => c.status !== 'resolved').length;
