/* =============================================================================
   CORRECTIONS

   Everything this app has got wrong and then fixed, dated, with the wrong
   version still readable. Most research sites in this subject have no such
   page, which is exactly why it is worth having one: a claim that has never
   been corrected is not the same as a claim that has never been wrong.

   Several of these were introduced by the assistant that built the app rather
   than by a source, and they are marked the same way as the rest. The point of
   the list is not to apportion blame but to let a reader see the failure rate.
   ========================================================================== */

export const CORRECTIONS = [
  {
    on: '2026-09-13',
    what: 'The app called the external tank fit established on the ground that there was no aerial refuelling, when its own record of the flight reports one.',
    wrong: 'The steelman labelled "He has the fuel" as "CITED: not a concession", because Bozeman to Albany is a single leg of 1,843 miles, longer than a clean two-seat F-16D flies, "and there was no aerial refuelling". Its summary said the leg was "flown nonstop as reported". The app\'s own record of the flight says the aircraft refuelled in the air roughly over Fargo on that leg.',
    right: 'One refuelling over Fargo splits the flight into two legs. Bozeman to Fargo is 687 miles, 0.69 times a clean two-seat F-16\'s range on the app\'s figure of 996 miles and 0.84 times on the USAF figure of 814. Fargo to Albany is 1,159 miles, 1.16 and 1.42 times. Tanks remain likely, but only if there was a single refuelling, and no record documents that. The tank fit is inferred, not established. The Montana-route result does not depend on it: about Mach 2.9 exceeds even a clean jet\'s Mach 2.0. The model is not recorded either. The FAA flight plan gives only F16/I, so the aircraft is a two-seat F-16, not an F-16D.',
    why: 'The fuel argument and the flight record sit in different files and were never read against each other.',
    rung: 'inferred',
  },
  {
    on: '2026-09-13',
    what: 'Gibney\'s documented flight that morning was said to have begun in Montana.',
    wrong: 'The brief said "His documented flight that morning began in Montana, which is what establishes the fuel tanks", and the walkthrough verdict said the same. Problem 4 of the walkthrough said the documented flight that establishes the tanks began in Montana.',
    right: 'His flight that morning began at Fargo. The Forum of Fargo-Moorhead, 2011: "The Pentagon was struck at some point as he headed toward Montana." The Montana departure was in the afternoon. FAA flight-data records at the National Archives (NAIDs 7599510 and 7601591) show an F-16, callsign NODAK99, on a route beginning at Bozeman, in Toronto Centre\'s hands by 17:39 EDT and arriving Albany at 18:49 EDT, then filed on to Langley as NODAC99. They do not name the pilot; the type, date, route and Langley leg match every account of his flight. At the filed 500 kt with no wind, the Bozeman departure works back to about 15:39 EDT, earlier if refuelling took time and later with a tailwind. For the eastbound leg this supersedes the app\'s statement that no source gives a time for any leg. It does not rule out the claim\'s own itinerary of Fargo, Shanksville, Bozeman, Albany: Shanksville to Bozeman is 1,667 miles, under three hours at cruise. When the aircraft landed at Bozeman is still unknown, and that is the deciding question. The tanks are inferred, not established, as the entry above explains.',
    why: 'The Fargo departure and the Bozeman departure were run together in a summary sentence, written before a time for either had been found.',
    rung: 'published',
  },
  {
    on: '2026-09-13',
    what: 'The list of unverified details said no source stated two things a source does state, and left the House Journal account unconfirmed.',
    wrong: 'It said no retrieved source states that Gibney asked to fly lower to reduce the stress on his passenger, that he flew over New York City after dark, or that he was airborne alongside Air Force One, and that all three had been removed. It listed the North Dakota House Journal of 16 January 2007 as unconfirmed because the PDF text could not be extracted.',
    right: 'InForum, 11 September 2019, by April Baumgarten, states the first two: "He asked for permission to fly at lower altitudes to ease stress on Jacoby", and "It was dark as he flew over New York City" after he dropped Jacoby. Air Force One appears there only as the exception to his being "the only plane in the sky", not as an aircraft he flew alongside. The earlier version of the app was right on two of the three, and removing them was the error. The House Journal has now been read. Its text, by David Somdahl, says: "119th Operations Group Commander, Lt. Col. Rick Gibney, returned Mr. Edward Jacoby to Albany on Sept. 11th, then flew on to the Langley Alert Detachment for duty." It gives no times.',
    why: 'Absence from the sources read at the time was recorded as absence from every source. The same 2019 article is already cited elsewhere in the app for the Bozeman airport. The House Journal item was not an error, only an open check that is now closed.',
    rung: 'published',
  },
  {
    on: '2026-09-13',
    what: 'A register entry said the Secret Service channel did not reach North Dakota.',
    wrong: 'Under the heading "It also does not reach North Dakota", the backchannel register entry said the arrangement ran between the executive and a unit guarding the capital, and that nothing resembling it connected the Secret Service to a transport tasking at Fargo.',
    right: 'It did reach North Dakota Guard pilots, at Langley rather than at Fargo. The Langley fighters, QUIT flight, were the 119th Fighter Wing\'s alert detachment. Miles Kara, from the audio: "At that time, 1028, the Secret Service first made sure they were in contact with Quit 25, the Langley lead pilot, via National TRACON on the DCA approach frequency." The Secret Service was working from a notional United 93 track on an FAA display, which faded at 10:28 when the projected aircraft reached Reagan National. That contact came 25 minutes after the crash. The 9/11 Commission says the Langley pilots never received "any type of engagement order" and were told "negative clearance to shoot" shortly after 10:10. No retrieved record connects the Secret Service to Gibney at Fargo.',
    why: 'The heading named the state when the argument was about Fargo. The app\'s own section on the military response quotes Maj. Gen. Mike Haugen describing a radio call to his pilots from someone identifying himself as the Secret Service.',
    rung: 'published',
  },
  {
    on: '2026-09-13',
    what: 'A correction on this page gave the wrong reason. It said the yaw damper channels were not working, and only two of them are.',
    wrong: 'The 2026-09-12 correction on the yaw axis said "The yaw damper channels are on the NTSB not-working list", as the basis for explaining why the rudder moved while the pedals did not.',
    right: 'Only YAW DAMPER ENGAGE L and R are on the not-working list, at Attachment I-10. YAW DAMPER - L, YAW DAMPER - R and YAW DAMPER MODULE are validated at Attachment I-7 and read OK throughout. A working yaw damper moves the rudder without moving the pedals, so the validated channels support the explanation rather than weaken it. The yaw axis stays excluded. The conclusion of the earlier correction stands and its stated reason does not.',
    why: 'This corrects a correction. The earlier entry was checked against the not-working list and not against the validated list for the same system.',
    rung: 'measured',
  },
  {
    on: '2026-09-13',
    what: 'The in-flight refuelling was attributed to Popular Mechanics as well as to InForum.',
    wrong: 'The record of the eastbound leg said the aircraft refuelled in the air roughly over Fargo, and cited Somdahl in Popular Mechanics, March 2005, alongside Roepke in The Forum of Fargo-Moorhead, 25 August 2011.',
    right: 'Popular Mechanics does not support it. The page the app links contains no text on Gibney, Jacoby, Bozeman or refuelling, and the Somdahl quote the app takes from Popular Mechanics does not mention refuelling. The only source for the refuelling so far is the 2011 InForum article: "Refueling in-air roughly above Fargo, Gibney and Jacoby flew back east."',
    why: 'Two sources were cited for a whole paragraph rather than sentence by sentence, so one of them was credited with a detail it does not contain.',
    rung: 'published',
  },
  {
    on: '2026-09-13',
    what: 'Vertical acceleration and engine N1 now rest on a direct read of the NTSB validated list rather than on absence.',
    wrong: 'The 2026-09-12 entry on the parameter audit said "Vertical acceleration and engine N1 still rest on absence rather than sight."',
    right: 'Both have been read directly. VERTICAL ACCELERATION, all eight channels, is on Attachment I-7, Parameters Validated. ENG N1-ACTUAL and ENG N2-ACTUAL for both engines are on Attachment I-3, also validated.',
    why: 'Not an error. The earlier entry stated the gap, and this records that it is closed.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'The apex of the final climb was given as 9,827 ft.',
    wrong: 'Repeated several times as the highest point the aircraft reached before the dive.',
    right: '9,902 ft at 10:02:15. The 9,827 figure is the value at the NTSB lettered anchor H, which sits five seconds past the apex and is not the maximum.',
    why: 'The anchor was read as though it were the peak. Found by a verification script written for the public data release, on its first run, which is the argument for writing one.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The parameter audit was reported as complete when two of its load-bearing entries were not checked.',
    wrong: 'The app said every cited recorder channel had been verified against the NTSB attachments.',
    right: 'Roll angle rested on a subagent report of a page nobody here had opened, and the engine channels rested on absence from a list read in fragments. Both have now been read directly and both hold: ROLL ANGLE CAPT at the tail of I-5, and ENG EPR-ACTUAL, FUEL FLOW and FUEL CUTOFF for both engines at the tail of I-2. Vertical acceleration and engine N1 still rest on absence rather than sight.',
    why: 'A reader pointed out that roll angle and engine symmetry carry the cascade argument and needed doing before the app leaned harder on them. They did, and the audit that claimed to have done it had not.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'A yaw-axis anomaly was reported as unexplained when it had a documented cause.',
    wrong: 'The app noted that the rudder moved while the rudder pedals did not, correlating at minus 0.055, and left it standing as an oddity.',
    right: 'The yaw damper channels are on the NTSB not-working list, and a yaw damper moves the rudder independently of the pedals by design. There was never anything to explain. The yaw axis is excluded.',
    why: 'Fell out of auditing every cited parameter against Attachment I, which is the check that should have preceded the observation rather than followed it.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'The app cited a flight recorder channel the NTSB had declared not working.',
    wrong: 'Hydraulic reservoir quantity was read off the tabulation and reported as though it were data.',
    right: 'HYD SYS LO QTY - C, - L and - R are all listed in Attachment I-9, Parameters Not Working or Unconfirmed. They should never have been cited. Hydraulic supply pressure and low-pressure, by contrast, are on the validated list at Attachment I-4, so those citations stand.',
    why: 'Presence in the published tabulation was treated as proof a parameter was good. It is not: the tabulation carries unvalidated channels too. Every parameter this app cites now needs checking against Attachment I, and that audit is open rather than done.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'A hydraulic pressure oddity was guessed at instead of checked.',
    wrong: 'The app said the 1,488 to 1,860 psi readings probably pointed at a decode scaling problem.',
    right: 'The scaling is correct and provably so. The parameter database defines HYD PRES as ten bits, y = 4x, range 0 to 4,092 psi, and all 237 published values are exact multiples of 4. The guess was wrong. What the check did find is that the recorder sampled this parameter every two seconds while the published tabulation shows it every sixty-four, so the blind window in the final dive is withheld data rather than absent data.',
    why: 'A reader asked for the oddity to be investigated rather than left flagged. Guessing at a cause and labelling the guess probable is the same error as asserting it.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The app said all three hydraulic systems read normal to three seconds before impact.',
    wrong: 'Presented as though the systems had been measured and found intact.',
    right: 'One threshold discrete read normal. The analogue pressure channels are sampled once every 64 seconds and stop at 10:02:18, 10:02:26 and 10:02:34, so the final dive has no analogue hydraulic data. And the reservoir quantity discrete reads LO QTY on 45 of 79 samples on the left system, which the app had not looked at before asserting the systems were clean.',
    why: 'A reader asked whether the hydraulic channels had blind spots like the cabin altitude one. They have three. The quantity indication turns out to be threshold chatter from before pushback rather than damage, but the app had claimed more than it had checked.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The app quoted half of a two-sentence paragraph and described the whole of it wrongly.',
    wrong: 'The 12 September brief was characterised as the intelligence community working from fragments the morning after, and only the first sentence of the al-Ghamdi paragraph was quoted.',
    right: 'Sentence one is a same-morning manifest match. Sentence two most likely reaches back into reporting already held, on the strength of the time-stamp pattern on page 1, where every fresh item is dated in the clear and this one is not. Both sentences are now quoted.',
    why: 'A reader asked whether that second sentence meant somebody had been tracking a hijacker. It does not, because the CIA wrote similar name and may have boarded. But the question exposed that the app was quoting the convenient half of a source, which is worse than the error it was defending against.',
    rung: 'inferred',
  },
  {
    on: '2026-09-12',
    what: 'The app argued that a recorder running to impact told against a warhead.',
    wrong: 'The walkthrough said the recorder ran coherently to impact, where a warhead normally stops one within milliseconds.',
    right: 'Most recorders in real missile cases keep running. Twenty-five minutes and a landing at Baghdad, about seventy-five minutes at Aktau, a hundred and four seconds at KAL 007, and PS752 recorded through the burst. The real discriminator is the systems cascade that follows, and United 93 has none.',
    why: 'A reader asked what a proximity fuze does to the argument. It defeats it, and the comparison set had already said so in material this app had read and not applied.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'The flight data recorder tabulation was described as unpublished.',
    wrong: 'The app said the engine, hydraulic and acceleration channels had never been released either way, and put that in the walkthrough.',
    right: 'They are published, in the NTSB flight data recorder factual report for DCA01MA065 of 15 February 2002. Peak vertical acceleration is +4.148 g and the minimum is -1.885 g, of 40,400 samples.',
    why: 'Nobody checked whether the factual report existed before asserting that it did not.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The inverted impact attitude was doubted on provenance grounds.',
    wrong: 'A register entry was opened questioning whether the NTSB badge on 40 degrees nose-down and inverted was earned.',
    right: 'ROLL ANGLE CAPT and PITCH ANGLE CAPT are validated recorded parameters. Roll passes 90 degrees at 10:03:03 and peaks at 161.4 degrees; pitch reaches minus 41.1 degrees. The badge was correct and the doubt was not.',
    why: 'Provenance was judged from the wording of a summary rather than from the parameter list behind it.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The recording was said to end with the aircraft still airborne.',
    wrong: 'The last sample of 2,189 ft was read as height above ground, implying 3.8 seconds of missing recording.',
    right: 'That is pressure altitude on the standard datum. The crash site terrain is about 2,370 ft above sea level, so on a normal high-pressure morning the aircraft was at ground level. Both recorders ran to impact.',
    why: 'A units error. Pressure altitude is not height above terrain.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The cabin pressure blind window was understated.',
    wrong: 'Given as roughly five minutes, from about 09:58.',
    right: 'The aircraft crossed below 10,000 ft at 09:54:51 and never regained it. The window is 09:54:50 to 10:03:09, eight minutes and nineteen seconds, and the revolt begins 130 seconds inside it.',
    why: 'Taken from a whole-minute anchor in a summary instead of from the recorded altitude.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'Passenger oxygen was cited as evidence against a hull breach.',
    wrong: 'The app noted that PASS OXY ON reads OFF throughout, as though that bore on whether the cabin was breached in the final minutes.',
    right: 'Masks deploy on a cabin altitude of about 14,000 ft, so below 10,000 ft that parameter is blind for the same reason the cabin discrete is. It says the masks never deployed. It says nothing about a breach in that window.',
    why: 'A true statement used to support something it does not support.',
    rung: 'absent',
  },
  {
    on: '2026-09-12',
    what: 'The GOFER 06 track put the crash site in the wrong place.',
    wrong: 'The drawn track never turned to 030 and placed the crash site at eleven or twelve o clock throughout, contradicting the radio call the app itself quotes.',
    right: 'Rebuilt from the two contemporaneous constraints. The site now sits at nine o clock, thirty miles off, across 10:04 to 10:06.',
    why: 'The track was drawn to look plausible rather than built from the call.',
    rung: 'derived',
  },
  {
    on: '2026-09-12',
    what: 'The smoke report was timed to 10:06.',
    wrong: 'Attributed to the 9/11 Commission at 10:06.',
    right: 'About 10:05. Note 170 of the Commission report puts the transmission about one minute thirty-seven seconds after impact, and the analyst the 10:06 came from explicitly disowns it as the time of the report.',
    why: 'A figure attached to the wrong sentence in the source.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'The United 93 ground track was too coarse to be honest.',
    wrong: 'Twenty-two points traced by eye from a printed map, with the 09:02 anchor about forty miles from its true position.',
    right: 'A 320-point polyline, validated against all nine of the lettered anchors in the study, with endpoints 0.37 and 0.28 miles from Newark and the crash site.',
    why: 'An approximation presented without saying how approximate.',
    rung: 'derived',
  },
  {
    on: '2026-09-12',
    what: 'The pilot of GOFER 06 was described as having witnessed the Shanksville crash.',
    wrong: 'The app said he watched it.',
    right: 'He saw a smoke column from about thirty miles, could not tell whether it came from the ground or the air, and put its top at 3,000 to 5,000 ft. The identification came from the controller, not the crew.',
    why: 'A witness account inflated in the retelling, by this app.',
    rung: 'published',
  },
  {
    on: '2026-09-12',
    what: 'The rolls were said to have thrown people around.',
    wrong: 'Described as bobbing occupants between 0.75 and 1.5 g.',
    right: 'The autopilot held altitude within about thirty feet throughout the rolling phase and lateral acceleration never exceeded 0.07 g. The floor tilted and the horizon went; there was very little vertical excursion. The Commission also says off balance, not off their feet.',
    why: 'A physical effect asserted before the altitude trace was read.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'A four-to-six g reading was offered as evidence of a manoeuvre rather than a weapon.',
    wrong: 'Stated as though the two were alternatives.',
    right: 'A false dichotomy: a warhead causes manoeuvres. After an R-98 detonated about fifty metres behind Korean Air 007, the entire recorded signature was a 113-second pitch-up from damaged elevator cabling.',
    why: 'A reasoning error, not a factual one, and the more dangerous kind.',
    rung: 'inferred',
  },
  {
    on: '2026-09-12',
    what: 'The steelman quoted a performance limit from a document that does not contain it.',
    wrong: 'The 600 KIAS placard for that stores configuration was attributed to T.O. 1F-16C-1.',
    right: 'That technical order gives the basic airspeed maximum and refers stores limits elsewhere. The figure traces to a forum post quoting a personal copy of a flight manual, reached only through search summaries.',
    why: 'The single most load-bearing number in the steelman, cited to the wrong document. It is now a concession rather than a citation.',
    rung: 'contested',
  },
  {
    on: '2026-09-12',
    what: 'The map could not be dragged on a phone.',
    wrong: 'The canvas set no touch-action, so the browser claimed each drag as a page scroll and cancelled it mid-motion. There was also no pinch zoom, and tapping a marker usually failed.',
    right: 'Fixed. One finger pans, two fingers pinch and rotate, and the tap threshold is fourteen pixels for touch rather than five.',
    why: 'Never tested under a finger.',
    rung: 'measured',
  },
  {
    on: '2026-09-12',
    what: 'The NTSB Flight Path Study was dated 12 February 2002.',
    wrong: 'Cited repeatedly with that date.',
    right: '19 February 2002.',
    why: 'A transcription error, repeated because nobody rechecked it.',
    rung: 'published',
  },
];

export const CORRECTIONS_NOTE =
  'Every one of these was published here in the wrong form first. The wrong version is '
  + 'kept beside the right one on purpose: a reader cannot judge how much to trust a source '
  + 'that only shows its final answers.';
